function neuronav_export_session_csv( ...
    sub_id, session, session_target, ...
    n_series, outputs_folder, ...
    trans_vox, target_vox, ...
    trans_mm, target_mm, ...
    trans_mni_vox, target_mni_vox, ...
    trans_mni_mm, target_mni_mm, ...
    interpolated)
% NEURONAV_EXPORT_SESSION_CSV
% Export per-session coordinate arrays to CSV with labeled voxel and RAS (mm) positions.

% INPUTS:
%   sub_id, session          : ID strings
%   session_target           : {N x 1} cell array with target labels
%   n_series                 : {N x 1} unused here (included for consistency)
%   outputs_folder           : path to save the output CSV
%   trans_vox, target_vox    : [N x 3] voxel coordinates in native (segmentation) space
%   trans_mm, target_mm      : [N x 3] RAS mm coordinates in native segmentation space
%   trans_mni_vox, target_mni_vox : [N x 3] voxel coordinates in MNI space
%   trans_mni_mm, target_mni_mm   : [N x 3] RAS mm coordinates in MNI space
%   interpolated                  : [logical] recorded (0) or inteprolated (1) coordinates 
% ---

N = size(trans_vox, 1);

variableTypes = [repmat({'string'},1,3), repmat({'double'},1,25)];
T = table('Size', [0 28], ...
          'VariableTypes', variableTypes, ...
          'VariableNames', ...
            {'id', 'session', 'target', ...
             'trans_native_vox_x', 'trans_native_vox_y', 'trans_native_vox_z', ...
             'target_native_vox_x', 'target_native_vox_y', 'target_native_vox_z', ...
             'trans_native_mm_x', 'trans_native_mm_y', 'trans_native_mm_z', ...
             'target_native_mm_x', 'target_native_mm_y', 'target_native_mm_z', ...
             'trans_MNI_vox_x', 'trans_MNI_vox_y', 'trans_MNI_vox_z', ...
             'target_MNI_vox_x', 'target_MNI_vox_y', 'target_MNI_vox_z', ...
             'trans_MNI_mm_x', 'trans_MNI_mm_y', 'trans_MNI_mm_z', ...
             'target_MNI_mm_x', 'target_MNI_mm_y', 'target_MNI_mm_z', ...
             'interpolated'});

for i = 1:N
    T(end+1,:) = {
        string(sub_id), ...
        string(session), ...
        string(strtrim(session_target{i})), ...
        trans_vox(i,1), trans_vox(i,2), trans_vox(i,3), ...
        target_vox(i,1), target_vox(i,2), target_vox(i,3), ...
        trans_mm(i,1), trans_mm(i,2), trans_mm(i,3), ...
        target_mm(i,1), target_mm(i,2), target_mm(i,3), ...
        trans_mni_vox(i,1), trans_mni_vox(i,2), trans_mni_vox(i,3), ...
        target_mni_vox(i,1), target_mni_vox(i,2), target_mni_vox(i,3), ...
        trans_mni_mm(i,1), trans_mni_mm(i,2), trans_mni_mm(i,3), ...
        target_mni_mm(i,1), target_mni_mm(i,2), target_mni_mm(i,3), ...
        interpolated
    };
end

outfile = fullfile(outputs_folder, sprintf('%s_info.csv', session));
writetable(T, outfile);

fprintf('Saved session info table (%d targets) → %s\n', N, outfile);
end

