function neuronav_export_session_csv( ...
    sub_id, session, session_target, ...
    outputs_folder, ...
    trans_vox, target_vox, ...
    trans_mm, target_mm, ...
    trans_mni_vox, target_mni_vox, ...
    trans_mni_mm, target_mni_mm, ...
    interpolated)
% NEURONAV_EXPORT_SESSION_CSV  Export per-session coordinates to a labelled CSV file
%
% Assembles native voxel, native RAS mm, MNI voxel, and MNI RAS mm
% coordinates into a table and writes it to CSV for downstream analyses.
%
% Use as:
%   neuronav_export_session_csv(sub_id, session, session_target, ...
%       outputs_folder, trans_vox, target_vox, trans_mm, target_mm, ...
%       trans_mni_vox, target_mni_vox, trans_mni_mm, target_mni_mm, interpolated)
%
% Input:
%   sub_id          - subject identifier string
%   session         - session identifier string
%   session_target  - {Nx1} cell array of target label strings
%   outputs_folder  - path to save the output CSV
%   trans_vox       - [Nx3] transducer voxel coordinates in native space
%   target_vox      - [Nx3] target voxel coordinates in native space
%   trans_mm        - [Nx3] transducer RAS coordinates in native space [mm]
%   target_mm       - [Nx3] target RAS coordinates in native space [mm]
%   trans_mni_vox   - [Nx3] transducer voxel coordinates in MNI space
%   target_mni_vox  - [Nx3] target voxel coordinates in MNI space
%   trans_mni_mm    - [Nx3] transducer RAS coordinates in MNI space [mm]
%   target_mni_mm   - [Nx3] target RAS coordinates in MNI space [mm]
%   interpolated    - logical flag: 0 = recorded, 1 = interpolated
%
% See also: NEURONAV_CONVERT_NATIVE_TO_MNI, NEURONAV_CONVERT_TRIGGER_TO_VOXELS

N = size(trans_vox, 1);

variableTypes = [repmat({'string'},1,3), repmat({'double'},1,25)];
T = table('Size', [0 28], ...
          'VariableTypes', variableTypes, ...
          'VariableNames', ...
            {'id', 'session', 'target', ...
             'trans_native_vox_x', 'trans_native_vox_y', 'trans_native_vox_z', ...
             'target_native_vox_x', 'target_native_vox_y', 'target_native_vox_z', ...
             'trans_native_mm_x', 'trans_native_mm_y', 'trans_native_mm_z', ...
             'target_native_mm_x', 'target_native_mm_y', 'target_native_mm_z', ...
             'trans_MNI_vox_x', 'trans_MNI_vox_y', 'trans_MNI_vox_z', ...
             'target_MNI_vox_x', 'target_MNI_vox_y', 'target_MNI_vox_z', ...
             'trans_MNI_mm_x', 'trans_MNI_mm_y', 'trans_MNI_mm_z', ...
             'target_MNI_mm_x', 'target_MNI_mm_y', 'target_MNI_mm_z', ...
             'interpolated'});

for i = 1:N
    T(end+1,:) = {
        string(sub_id), ...
        string(session), ...
        string(strtrim(session_target{i})), ...
        trans_vox(i,1), trans_vox(i,2), trans_vox(i,3), ...
        target_vox(i,1), target_vox(i,2), target_vox(i,3), ...
        trans_mm(i,1), trans_mm(i,2), trans_mm(i,3), ...
        target_mm(i,1), target_mm(i,2), target_mm(i,3), ...
        trans_mni_vox(i,1), trans_mni_vox(i,2), trans_mni_vox(i,3), ...
        target_mni_vox(i,1), target_mni_vox(i,2), target_mni_vox(i,3), ...
        trans_mni_mm(i,1), trans_mni_mm(i,2), trans_mni_mm(i,3), ...
        target_mni_mm(i,1), target_mni_mm(i,2), target_mni_mm(i,3), ...
        interpolated
    };
end

outfile = fullfile(outputs_folder, sprintf('%s_%s_info.csv', sub_id, session));
writetable(T, outfile);

fprintf('Saved session info table (%d targets) → %s\n', N, outfile);
end

