function [job_id, parameters] = hpc_submit_job(hpc_type, temp_m_file, parameters, log_dir)
% HPC_SUBMIT_JOB  Write a scheduler script and submit a MATLAB job to SLURM or qsub
%
% Generates a temporary scheduler script (SLURM .sh or PBS .sh) from the
% parameters struct, submits it, and returns the assigned job ID. Also handles
% Snellius-specific parameter extraction when parameters.hpc.name = 'snellius'.
% The second output (parameters) is returned because Snellius extraction may
% modify hpc fields in place.
%
% Use as:
%   [job_id, parameters] = hpc_submit_job(hpc_type, temp_m_file, parameters, log_dir)
%
% Input:
%   hpc_type    - 'slurm' or 'qsub'
%   temp_m_file - basename of the temporary .m script (no path, no extension);
%                 generated by hpc_setup_temp_files
%   parameters  - PRESTUS config struct; relevant fields:
%                   .subject_id, .hpc.name, .hpc.partition, .hpc.memory_gb,
%                   .hpc.timelimit, .hpc.n_workers, .hpc.job_name
%   log_dir     - path to the batch_job_logs directory
%
% Output:
%   job_id     - scheduler job ID (numeric for SLURM, string for qsub)
%   parameters - (possibly modified) parameters struct; hpc fields may be
%                updated by Snellius-specific extraction
%
% See also: HPC_DETECT_SYSTEM, HPC_SETUP_TEMP_FILES, HPC_WAIT_FOR_COMPLETION

subj_id_string = sprintf('sub-%03d', parameters.subject_id);

switch hpc_type
    case 'slurm'
        temp_slurm_path = fullfile(log_dir, sprintf('temp_slurm_%s.sh', datestr(now, 'yyyymmdd_HHMMSS')));

        % Define HPC type
	    if ~isfield(parameters.hpc, 'name')
            parameters.hpc.name = 'default';
        end
    
	    % Overwrite and extract additional parameters if Snellius HPC
	    if strcmp(parameters.hpc.name, 'snellius')
		    [parameters] = extract_snellius_parameters(parameters);
	    end
        
        write_slurm_script(temp_slurm_path, parameters, temp_m_file, log_dir);
        job_id = submit_slurm_job(temp_slurm_path, log_dir);

    case 'qsub'
        temp_qsub_path = fullfile(log_dir, sprintf('temp_qsub_%s.sh', datestr(now, 'yyyymmdd_HHMMSS')));
        write_qsub_script(temp_qsub_path, parameters, temp_m_file, log_dir);
        job_id = submit_qsub_job(temp_qsub_path, log_dir);

    otherwise
        error('Unsupported HPC type: %s', hpc_type);
end

fprintf('Job "%s" (ID: %s) submitted successfully\n', hpc_job_name(parameters), sprintf('%d', job_id));

% ========== LOCAL FUNCTIONS ==========
function write_slurm_script(temp_slurm_path, parameters, temp_m_file, log_dir)
    subj_id_string = sprintf('sub-%03d', parameters.subject_id);
    job_name = hpc_job_name(parameters);
	
    fid = fopen(temp_slurm_path, 'w+');
    fprintf(fid, '#!/bin/bash\n');
    fprintf(fid, '#SBATCH --job-name=%s\n', job_name);
    
    % Partition & GPU detection
    needs_gpu = (isfield(parameters.simulation, 'code_type') && any(strcmp(parameters.simulation.code_type, {'matlab_gpu', 'cpp_gpu'})));
    
    if isfield(parameters.hpc, 'partition') && ~isempty(strtrim(char(parameters.hpc.partition)))
        fprintf(fid, '#SBATCH --partition=%s\n', strtrim(char(parameters.hpc.partition)));
    elseif needs_gpu
        fprintf(fid, '#SBATCH --partition=gpu\n');
    end

    if strcmp(parameters.hpc.name, 'snellius')
		fprintf(fid, '#SBATCH --gpus=%i\n', parameters.hpc.n_gpu);
    elseif isfield(parameters.hpc, 'gpu') && ~isempty(strtrim(char(parameters.hpc.gpu)))
        fprintf(fid, '#SBATCH --gres=%s\n', strtrim(char(parameters.hpc.gpu)));
    elseif needs_gpu
        fprintf(fid, '#SBATCH --gres=gpu:1\n');
    end

    if isfield(parameters.hpc, 'reservation') && ~isempty(strtrim(char(parameters.hpc.reservation)))
        fprintf(fid, '#SBATCH --reservation=%s\n', strtrim(char(parameters.hpc.reservation)));
    end

	if strcmp(parameters.hpc.name, 'snellius')
        fprintf(fid, '#SBATCH --cpus-per-task=%i\n', parameters.hpc.cores);
    end

    fprintf(fid, '#SBATCH --mem=%iG\n', parameters.hpc.memorylimit);
    fprintf(fid, '#SBATCH --time=%s\n', parameters.hpc.timelimit);
    fprintf(fid, '#SBATCH --output=%s_slurm_output_%%j.log\n', subj_id_string);
    fprintf(fid, '#SBATCH --error=%s_slurm_error_%%j.log\n', subj_id_string);
    fprintf(fid, '#SBATCH --chdir=%s\n', log_dir);

    % Job dependencies (used by uncertainty pipeline for stage chaining).
    % --kill-on-invalid-dep=yes ensures that if the predecessor fails or is
    % cancelled, all dependent jobs are automatically cancelled rather than
    % remaining stuck as DependencyNeverSatisfied indefinitely.
    if isfield(parameters.hpc, 'depend_job_ids') && ~isempty(parameters.hpc.depend_job_ids)
        dep_str = strjoin(arrayfun(@(x) num2str(x), parameters.hpc.depend_job_ids, ...
            'UniformOutput', false), ':');
        fprintf(fid, '#SBATCH --dependency=afterok:%s\n', dep_str);
        fprintf(fid, '#SBATCH --kill-on-invalid-dep=yes\n');
    elseif isfield(parameters.hpc, 'depend_job_id') && ~isempty(parameters.hpc.depend_job_id)
        fprintf(fid, '#SBATCH --dependency=afterok:%d\n', parameters.hpc.depend_job_id);
        fprintf(fid, '#SBATCH --kill-on-invalid-dep=yes\n');
    end
    
    if needs_gpu, fprintf(fid, 'nvidia-smi\n'); end
	if strcmp(parameters.hpc.name, 'snellius')
        fprintf(fid, 'module load 2024\n');
        fprintf(fid, 'module load MATLAB/2024b\n');
    else
		fprintf(fid, 'module load matlab/R2023b\n');
	end
    fprintf(fid, 'matlab -batch "%s"\n', temp_m_file);
    fclose(fid);
end

function [parameters] = extract_snellius_parameters(parameters)
	
    switch parameters.hpc.partition
        case 'gpu_a100'
            parameters.hpc.memorylimit = parameters.snellius.gpu_a100.memorylimit;
            parameters.hpc.cores = parameters.snellius.gpu_a100.cores;
            max_timelimit = parameters.snellius.gpu_a100.timelimit;
            parameters.hpc.n_gpu = parameters.snellius.gpu_a100.n_gpu;
        case 'gpu_h100'
            parameters.hpc.memorylimit = parameters.snellius.gpu_h100.memorylimit;
            parameters.hpc.cores = parameters.snellius.gpu_h100.cores;
            max_timelimit = parameters.snellius.gpu_h100.timelimit;
            parameters.hpc.n_gpu = parameters.snellius.gpu_h100.n_gpu;
        otherwise
            error('GPU %s is unknown or not implemented for Snellius.', parameters.hpc.partition)
    end

    assert(parameters.hpc.timelimit <= max_timelimit, ...
        'Maximum wall time of %s is exceeded (%s).', ...
        max_timelimit, ...
        parameters.hpc.timelimit)
end

function job_id = submit_slurm_job(temp_slurm_path, log_dir)
    sbatch_call = sprintf('sbatch %s', temp_slurm_path);
    full_cmd = sprintf('cd %s; %s', log_dir, sbatch_call);
    
    fprintf('SLURM command: %s\n', full_cmd);
    [status, out] = system(full_cmd);
    if status ~= 0, error('SLURM submission failed: %s', out); end
    
    job_ids = regexp(out, '\d+', 'match');
    if isempty(job_ids), error('No SLURM job ID returned'); end
    job_id = str2double(job_ids{1});
end

function write_qsub_script(temp_qsub_path, parameters, temp_m_file, log_dir)
    subj_id_string = sprintf('sub-%03d', parameters.subject_id);
    job_name = hpc_job_name(parameters);
    
    fid = fopen(temp_qsub_path, 'w+');
    fprintf(fid, '#!/bin/bash\n');
    fprintf(fid, '#PBS -N %s\n', job_name);
    fprintf(fid, '#PBS -l nodes=1:gpus=1,feature=cuda,reqattr=cudacap>=8.0,mem=%iGb,walltime=%i\n', ...
        parameters.hpc.memorylimit, parameters.hpc.timelimit);
    fprintf(fid, '#PBS -o %s_qsub_output_%%j.log\n', subj_id_string);
    fprintf(fid, '#PBS -e %s_qsub_error_%%j.log\n', subj_id_string);
    fprintf(fid, '#PBS -d %s\n', log_dir);

    % Job dependencies (used by uncertainty pipeline for stage chaining)
    if isfield(parameters.hpc, 'depend_job_ids') && ~isempty(parameters.hpc.depend_job_ids)
        dep_str = strjoin(arrayfun(@(x) num2str(x), parameters.hpc.depend_job_ids, ...
            'UniformOutput', false), ':');
        fprintf(fid, '#PBS -W depend=afterok:%s\n', dep_str);
    elseif isfield(parameters.hpc, 'depend_job_id') && ~isempty(parameters.hpc.depend_job_id)
        fprintf(fid, '#PBS -W depend=afterok:%d\n', parameters.hpc.depend_job_id);
    end
	fprintf(fid, 'module load matlab/R2023b\n');
    fprintf(fid, 'matlab -batch "%s"\n', temp_m_file);
    fclose(fid);
end

function job_id = submit_qsub_job(temp_qsub_path, log_dir)
    qsub_call = sprintf('qsub %s', temp_qsub_path);
    full_cmd = sprintf('cd %s; %s', log_dir, qsub_call);
    
    fprintf('qsub command: %s\n', full_cmd);
    [status, out] = system(full_cmd);
    if status ~= 0, error('qsub submission failed: %s', out); end
    job_id = strtrim(out);
end
end
