# The configuration is structured using YAML (https://yaml.org/). Note that YAML uses spaces, not tabs, for identation.

# paths to where the data is stored and to the simnibs environment
data_path: /project/3015999.02/andche_sandbox/TUS_sims/tusim/data
simnibs_env_path: /project/3015999.02/andche_sandbox/simnibs/simnibs_env

overwrite_files: ask # 'never' to never overwrite, 'always' to always overwrite, any other value to ask for confirmation
overwrite_simnibs: 0 # simnibs segmentation results are not overwritten, regardless of anything else, unless enabled here (by setting to 1)

interactive: 1 # in interactive mode (1), the figures are shown and confirmation dialogs appear in non-interactive mode (0), no plots are shown and no confirmation dialogs (not fully implemented)
simulation_medium: water_and_skull # select which medium setup to use: 'water', 'water_and_skull', 'brain', 'brain_and_skull' (the latter two assume "brain" parameters everywhere, also outside of brain), or 'layered'
layer_labels:  # labels for layered simulation, assuming for now the SimNIBS masks indices; note that the labels are applied in the order specified here, so the skull should normally be the last as it matters the most
  water: [0, 6, 7, 8]
  brain: [1, 2]
  skin: [5]
  skull: [4]

t1_path_template: sub-%1$03d_orig_T1w.nii.gz # path to T1 relative to data_path; all string substitutions will be done using subject_id
t2_path_template: sub-%1$03d_orig_T2w.nii.gz # path to T2 relative to data_path; all string substitutions will be done using subject_id

# if the simulations are done for water only, set the grid size manually
# select the desired simulation grid size (number of points per dimension)
default_grid_size: 144
default_grid_dims: [144, 144, 256]

# medium properties, references: ITRUST benchmarks (https://arxiv.org/abs/2202.04552); Tissue Properties DB (https://itis.swiss/virtual-population/tissue-properties/overview/);
medium:
  water:
    sound_speed: 1500 # [m/s] ITRUST benchmarks 
    density: 994 # [kg/m^3] Tissue Properties DB or waterDensity(37) function in kWave
    alpha_0_true: 0  # from ITRUST benchmarks at 500 kHz (assumes no absorption in water, so no heating )
    alpha_power_true: 1
    thermal_conductivity: 0.60 # (W/m/°C) Tissue Properties DB
    specific_heat_capacity: 4178 # (J/kg/°C) Tissue Properties DB
  skull: # cortical bone
    sound_speed: 2800 # [m/s], ITRUST benchmarks 
    density: 1850 # [kg/m^3], ITRUST benchmarks
    alpha_0_true: 8 # ITRUST benchmarks [this is alpha_0 in alpha = alpha_0*frequency^alpha_power]
    alpha_power_true: 1
    thermal_conductivity: 0.32 # (W/m/°C) Tissue Properties DB 
    specific_heat_capacity: 1313 # (J/kg/°C) Tissue Properties DB
  brain:
    sound_speed: 1546 # [m/s] Tissue Properties DB 
    density: 1046 # [kg/m^3], ITRUST benchmarks or waterDensity(temp_0)
    alpha_0_true: 0.6 # ITRUST benchmarks 
    alpha_power_true: 1
    thermal_conductivity: 0.51 # (W/m/°C) Tissue Properties DB 
    specific_heat_capacity: 3630 # (J/kg/°C) Tissue Properties DB 
  skin:
    sound_speed: 1610 # [m/s], ITRUST benchmarks 
    density: 1090 # [kg/m^3], ITRUST benchmarks
    alpha_0_true: 0.4 # ITRUST benchmarks 
    alpha_power_true: 1
    thermal_conductivity: 0.37 # (W/m/°C) Tissue Properties DB 
    specific_heat_capacity: 3391 # (J/kg/°C) Tissue Properties DB


default_freq: 0.5e6 # the default frequency used to calculate the medium parameters above

transducer:  # defaults for the transducer
  n_elements: 4 # number of elements in the transducer
  Elements_ID_mm: [0, 32.9184, 46.1264, 56.0324]
  Elements_OD_mm: [32.3596, 45.5676, 55.5244, 64.008]
  curv_radius_mm: 63.20 # radius of curvature of the bowl 
  dist_to_plane_mm: 52.38 # distance to the transducer plane from the geometric focus
  source_amp: 91590 # [Pa] 
  source_phase_deg: [0.0, 13.2, 26.4, 52.8] # source phase [deg] 
  source_freq_hz: 250e3 # [Hz] the central frequency
  pos_t1_grid: [128, 139, 15] # position on T1 grid 

focus_pos_t1_grid: [128, 142, 75] # stimulation target on T1 grid

focus_area_radius: 5 # radius of the target area around the focus in which the ISPPA is averaged for the outputs, mm

# default parameters for thermal simulations
thermal:
  duty_cycle: 1 # share of the stimulation duration during which the stimulation is on
  sim_time_steps: 0.1 # [s] simulation time steps during the stimulation period
  temp_0: 37 #[deg C] initial temperature, currently not used
  stim_duration: 0.6 # [s] stimulation duration within a trial
  iti: 0.6 # interval between the trials, from the start of one trial to the start of another [s]
  n_trials: 12 # number of trials to simulate; the total simulated duration is then n_trials*iti seconds
  sensor_xy_halfsize: 100 # maximum size of the sensor window in which the temperature is recorded (in grid units)
  record_t_at_every_step: 0 # should we record temperature for every time step _for the whole sensor window_ (memory intensive, turn off if you experience 'out of memory' issues)

# select which k-Wave code to run
#   MATLAB CPU code 'matlab_cpu'
#   MATLAB GPU code 'matlab_gpu'
#   C++ code (Interactive) 'cpp_interactive'
#   C++ code (Non-Interactive) 'cpp_noninteractive'
#   CUDA code 'cuda' (currently does not work at the Donders HPC, but 'matlab_gpu' works)

code_type: matlab_gpu 

# select PML size, the default one for 3D is 10 (PML is the layer used in
# kWaves to absorb waves reaching the end of the computational grid,
# http://www.k-wave.org/documentation/example_na_controlling_the_pml.php)
pml_size: 10

# grid resolution (must be isotropic) 
grid_step_mm: 0.5  # [mm]

# optional affix for result files names
results_filename_affix: ''

# expansion factor for the cerebro-spinal fluid brain mask; if the mask ends up too big, try reducing it (40 is the conservative default; the mask is dilated with csf_mask_expansion_factor/voxel_size_mm cubic kernel)
csf_mask_expansion_factor: 40

# use the kwaveArray class for simulations
use_kWaveArray: 0

skull_smooth_threshold: 0.35 # threshold for smoothing the skull mask (higher threshold means thinner mask, lower threshold means thicker mask)
other_smooth_threshold: 0.5 # threshold for smoothing other masks (higher threshold means thinner mask, lower threshold means thicker mask)
prime_factor_max_grid_expansion: 40 # how much the computational grid can be expanded in order to get lower prime numbers to (potentially) speed up computations

run_source_setup: 1 # should we set up acoustic source? useful to switch off to look at initial segmentation results only
run_acoustic_sims: 1 # should we run the acoustic simulations? useful to switch off to look at initial segmentation results only
run_heating_sims: 0 # should we run the heating simulations? useful to switch off to look at initial segmentation results only
run_posthoc_water_sims: 0 # should we run the simulations in free water with exactly the same parameter? useful for double checking that the true intensity matches the desired one