transducer: 
  n_elements: 1 # number of elements in the transducer
  Elements_ID_mm: [0] # element inner diameter [mm]
  Elements_OD_mm: [64.0] # element outer diameter [mm]
  curv_radius_mm: 64.00 # radius from the focal point to the bowl outermost point [mm]
  source_amp: [60e3]  # [Pa] (60 kPa)
  source_phase_rad: [0] # [rad] 
  source_freq_hz: 500e3  # [Hz]
  pos_grid: [71, 1]


expected_focal_distance_mm: 64.0 # expected distance to the stimulation focus, mm
transducer_from_localite: 0 # transducer position is to be taken from the localite file

default_grid_dims: [141, 241]

grid_step_mm: 0.5

use_kWaveArray: 0