function error = phase_optimization_annulus(phase, parameters, velocity, axial_position, desired_focal_dist_mm)
  p_axial_oneil = focusedAnnulusONeil(parameters.transducer.curv_radius_mm/1e3, ...
    [parameters.transducer.Elements_ID_mm; parameters.transducer.Elements_OD_mm]/1e3, repmat(velocity,1,4), ...
    [0, phase(1), phase(2), phase(3)], parameters.transducer.source_freq_hz, parameters.medium.water.sound_speed, ...
    parameters.medium.water.density, (axial_position-0.5)*1e-3);
  actual_focal_dist_mm = axial_position(p_axial_oneil==max(p_axial_oneil));
  error = abs(desired_focal_dist_mm-actual_focal_dist_mm);
end