data_path: /home/visual/andche/STAFF_SCI/andche_sandbox/Sjoerd_MRI/
t1_path_template: MRI/sub-%1$03d/ses-mri01/anat/*T1w.nii.gz
t2_path_template: MRI/sub-%1$03d/ses-mri01/anat/*T2w.nii.gz

transducer: 
  n_elements: 4 # number of elements in the transducer
  Elements_ID_mm: [0, 32.9184, 46.1264, 56.0324]
  Elements_OD_mm: [32.3596, 45.5676, 55.5244, 64.008]
  curv_radius_mm: 63.20 # radius of curvature of the bowl 
  dist_to_plane_mm: 52.38 # distance to the transducer plane from the geometric focus
  source_amp: 145103 # [Pa] (calibrated values at 20 W/cm^2 free-water Isppa)
  source_phase_deg: [0, 0, 358.0546, 272.2390] # source phase [deg] (calibrated values at 20 W/cm^2 free-water Isppa)
  source_freq_hz: 250e3 # [Hz] the central frequency

transducer_from_localite: 0 # should we load the transducer locations from the localite file(s) 
thermal:
  duty_cycle: 0.3 # share of the stimulation duration during which the stimulation is on
  on_off_step_duration: 0.1 # duration of the on+off cycle (e.g., with a duty cycle of 0.3 and 0.01 s time steps for simulation, the whole on+off cycle will take 0.1 s)
  equal_steps: 0 # is the duration of the simulation steps equal for on and off steps? if not, it is computed based on the sim_time_steps * n_steps where n_steps is the needed number of on and off steps derived from the duty cycle
  sim_time_steps: 0.01 # [s] simulation time steps during the stimulation period
  post_stim_time_step_dur: 0.1 # post-stimulation (inter-trial) steps
  stim_duration: 3 # [s] stimulation duration within a trial
  iti: 9 # interval between the trials, from the start of one trial to the start of another [s]
  n_trials: 4 # number of trials to simulate; the total simulated duration is then n_trials*iti seconds
