subject_subfolder: 1 # Should each participants output be stored in a separate folder?

t1_path_template: /*T1.nii.gz
t2_path_template: /*T2.nii.gz

transducer: 
  n_elements: 4 # number of elements in the transducer
  Elements_ID_mm: [0, 32.9184, 46.1264, 56.0324]
  Elements_OD_mm: [32.3596, 45.5676, 55.5244, 64.008]
  curv_radius_mm: 63.20 # radius of curvature of the bowl 
  dist_to_plane_mm: 52.38 # distance to the transducer plane from the geometric focus
  source_amp: 143000 # [Pa] (143000 calibrated values at 30 W/cm^2 free-water Isppa, 166500 at 40 W/cm^2, 184200 for 50 W/cm^2)
  source_phase_deg: [0, 0, 358.0546, 272.2390] # source phase [deg] (calibrated values at 20 W/cm^2 free-water Isppa)
  source_freq_hz: 250e3 # [Hz] the central frequency

expected_focal_distance_mm: 64.5 # expected distance to the stimulation focus
transducer_from_localite: 0 # should we load the transducer locations from the localite file(s)

using_donders_hpc: 1 # are the simulations run on the HPC cluster?

run_posthoc_water_sims: 1
run_heating_sims: 1

medium:
  skull:
    alpha_0_true: 8

thermal:
  duty_cycle: 0.5 # share of the stimulation duration during which the stimulation is on
  sim_time_steps: 0.1 # [s] simulation time steps during the stimulation period
  temp_0: 37 #[deg C] initial temperature, currently not used
  stim_duration: 120 # [s] stimulation duration within a trial
  iti: 0 # interval between the trials, from the start of one trial to the start of another [s]
  n_trials: 1 # number of trials to simulate; the total simulated duration is then n_trials*iti seconds
