transducer: 
  n_elements: 2 # number of elements in the transducer
  Elements_ID_mm: [0, 32.6644] # elements 1 & 2 inner diameter [mm]
  Elements_OD_mm: [32.1564, 45.4914] # element 1 & 2 outer diameter [mm]
  curv_radius_mm: 63.20 # radius from the focal point to the bowl outermost point
  dist_to_plane_mm: 56.87 # distance to the transducer plane from the geometric focus
  source_amp: 122277 # [Pa] (calibrated values at 20 W/cm^2 free-water Isppa)
  source_phase_rad: [0, 2.0381] # [rad] (calibrated values at 20 W/cm^2 free-water Isppa)
  source_freq_hz: 250e3  # [Hz]


expected_focal_distance_mm: 28.0 # expected distance to the stimulation focus
transducer_from_localite: 1 # transducer position is to be taken from the localite file

# distance from the reference used in the neuronavigation (could be the TMS coil or the three-ball reference) and the transducer
reference_transducer_distance_mm: 18

data_path: /project/2422024.01/M1TUS_2

t1_path_template: P%1$02d/*_T1w.nii.gz # path to T1 relative to data_path; all string substitutions will be done using subject_id
t2_path_template: P%1$02d/*_T2w.nii.gz # path to T2 relative to data_path; all string substitutions will be done using subject_id
localite_instr_file_template: P%1$02d/Instrument*.xml  # path to the localite file that has the data about the instrument relative to data_path; could also be a template similar to t1 and t2 path (usually an xml file taken from subject/Sessions/Session_xxxx/InstrumentMarkers/ folder)

run_heating_sims: 1

default_grid_dims: [144, 144, 256]

thermal:
  duty_cycle: 0.3 # share of the stimulation duration during which the stimulation is on
  on_off_step_duration: 0.1 # duration of the on+off cycle (e.g., with a duty cycle of 0.3 and 0.01 s time steps for simulation, the whole on+off cycle will take 0.1 s)
  equal_steps: 0 # is the duration of the simulation steps equal for on and off steps? if not, it is computed based on the sim_time_steps * n_steps where n_steps is the needed number of on and off steps derived from the duty cycle
  sim_time_steps: 0.01 # [s] simulation time steps during the stimulation period
  post_stim_time_step_dur: 0.1 # post-stimulation (inter-trial) steps
  stim_duration: 0.5 # [s] stimulation duration within a trial
  iti: 5 # interval between the trials, from the start of one trial to the start of another [s]
  n_trials: 2 # number of trials to simulate; the total simulated duration is then n_trials*iti seconds
