<<<<<<<< HEAD:configs/sjoerd_config_opt_CTX250-001_203_60.9mm.yaml
# Location of stored data
data_path: /project/3023001.06/Simulations/data_for_prestus/
simnibs_bin_path: /home/affneu/kenvdzee/SimNIBS-4.0/bin/
subject_subfolder: 1
output_location: /project/3023001.06/Simulations/data_for_prestus/250KHz/40W_per_cm2_new/CTX250-001/

overwrite_simnibs: 0

# Structure of subfolders containing T1 and T1 images
## It is easier to store the subject data of each participant in an individual subfolder
t1_path_template: sub-%1$03d/*t1mprage*T1w.nii.gz
t2_path_template: sub-%1$03d/*t2space*T2w.nii.gz

transducer: 
  n_elements: 4 # number of elements in the transducer
  Elements_ID_mm: [0, 30.1788, 42.1388, 51.1088]
  Elements_OD_mm: [29.62, 41.58, 50.55, 57.94]
  curv_radius_mm: 62.94 # radius of curvature of the bowl 
  dist_to_plane_mm: 52.38 # distance to the transducer plane from the geometric focus
  source_amp: 199270 # [Pa]
  source_phase_deg: [0, 300.544203, 308.222241, 283.413768] # source phase [deg]
  source_freq_hz: 250e3 # [Hz] the central frequency

expected_focal_distance_mm: 60.9 # expected distance to the stimulation focus
transducer_from_localite: 0 # should we load the transducer locations from the localite file(s) 

using_donders_hpc: 1 # are the simulations run on the HPC cluster?
charm_debug: 0
overwrite_simnibs: 0
use_forceqform: 0

run_posthoc_water_sims: 1
run_heating_sims: 1

thermal:
  duty_cycle: 0.3 # share of the stimulation duration during which the stimulation is on [0 to 1] (trial length = duty_cycle * stim_duration)
  iti: 14 # [s] interval between the trials, from the start of one trial to the start of another
  n_trials: 2 # number of trials to simulate; the total simulated duration is then n_trials*iti seconds
  stim_duration: 1 # [s] stimulation duration within a trial
  # Pulse repetition frequency is not used since the cooling effects between these cycles are limited

  # These should only be changed if they don't meet the criteria described in "run_heating_simulations"
  sim_time_steps: 0.01 # [s] simulation time steps during the stimulation period
  post_stim_time_step_dur: 0.1 # post-stimulation (inter-trial) steps
  on_off_step_duration: 0.1 # duration of the on+off cycle (e.g., with a duty cycle of 0.3 and 0.01 s time steps for simulation, the whole on+off cycle will take 0.1 s)
  equal_steps: 0 # is the duration of the simulation steps equal for on and off steps? if not, it is computed based on the sim_time_steps * n_steps where n_steps is the needed number of on and off steps derived from the duty cycle
========
# Location of stored data
data_path: /project/3023001.06/data/ #/project/3023001.06/eleonora/new_segmentations/   #/project/3023001.06/Simulations/data_for_prestus/ 
subject_subfolder: 1 # Should each participants output be stored in a separate folder?
output_location: simulations_charm_T1_T2/new_alpha/    #t1_utet2/     

# Structure of subfolders containing T1 and T1 images
## It is easier to store the subject data of each participant in an individual subfolder
#t1_path_template: sub-%1$03d/*T1w.nii.gz  
#t1_path_template: sub-%1$03d/*petratranoInversion_run-1_T1w.nii.gz
t1_path_template: sub-%1$03d/ses-tus01/simu/*mpragesagp20p9iso_run-1_T1w.nii.gz #normal T1 with new folder structure
#t2_path_template: sub-%1$03d/*T2w.ni.gz   
#t2_path_template: sub-%1$03d/*petratranoInversion2degrees120000spokes_run-1_T2w.nii.gz #ute
t2_path_template: sub-%1$03d/ses-tus01/simu/*sagp20p9iso_run-1_T2w.nii.gz #normal t2

transducer: 
  n_elements: 4 # number of elements in the transducer
  Elements_ID_mm: [0, 32.9184, 46.1264, 56.0324]
  Elements_OD_mm: [32.3596, 45.5676, 55.5244, 64.008]
  curv_radius_mm: 63.20 # radius of curvature of the bowl 
  dist_to_plane_mm: 52.38 # distance to the transducer plane from the geometric focus
  source_amp: 166500 # [Pa] (143000 calibrated values at 30 W/cm^2 free-water Isppa, 166500 at 40 W/cm^2, 184200 for 50 W/cm^2, 156200 for 36 W/cm^2)
  source_phase_deg: [0, 9.9454e-07, 354.4105, 271.8960] # source phase [deg] (calibrated values at 20 W/cm^2 free-water Isppa)
  source_freq_hz: 250e3 # [Hz] the central frequency

expected_focal_distance_mm: 64.5 # expected distance to the stimulation focus
transducer_from_localite: 0 # should we load the transducer locations from the localite file(s) --> always use 0 because this
# is a old function from judith!! it loads them anyway with sjoerd way

using_donders_hpc: 1 # are the simulations run on the HPC cluster?

use_forceqform: 1

#do you have a pseudoCT? if yes, set usepseudoCT=1
usepseudoCT: 0

run_posthoc_water_sims: 1
run_heating_sims: 1

medium:
  skull:
    alpha_0_true: 8

thermal:
  duty_cycle: 0.4 # share of the stimulation duration during which the stimulation is on [0 to 1] (trial length = duty_cycle * stim_duration)
  iti: 9 # [s] interval between the trials, from the start of one trial to the start of another
  n_trials: 30 # number of trials to simulate; the total simulated duration is then n_trials*iti seconds
  stim_duration: 1 # [s] stimulation duration within a trial
  # Pulse repetition frequency is not used since the cooling effects between these cycles are limited

  # These should only be changed if they don't meet the criteria described in "run_heating_simulations"
  sim_time_steps: 0.01 # [s] simulation time steps during the stimulation period
  post_stim_time_step_dur: 0.1 # post-stimulation (inter-trial) steps
  on_off_step_duration: 0.2 #0.1 # duration of the on+off cycle (e.g., with a duty cycle of 0.3 and 0.01 s time steps for simulation, the whole on+off cycle will take 0.1 s)
  equal_steps: 0 # is the duration of the simulation steps equal for on and off steps? if not, it is computed based on the sim_time_steps * n_steps where n_steps is the needed number of on and off steps derived from the duty cycle
  
>>>>>>>> pseudoCT:configs/sjoerd_config_opt_CTX250-011_64.5mm.yaml
