# The configuration is structured using YAML (https://yaml.org/).
# Note that YAML uses spaces, not tabs, for indentation.

# !!! Important !!!
# This file is a user config derived from default_config.yaml + base_config_BFTUS.yaml

# Paths to the data location and SimNIBS environment (please use full paths)
data_path: /project/2425076.01/sims/data/
seg_path: /project/2425076.01/mri/seg/
simnibs_bin_path: /opt/simnibs/4.0.0/simnibs_env/bin/

# Paths to T1 and T2 relative to data_path; all string substitutions will be done using subject_id
t1_path_template: sub-%1$03d_T1.nii.gz
t2_path_template: sub-%1$03d_T2.nii.gz
# default examples in dev:
# t1_path_template: sub-%1$03d_orig_T1w.nii.gz
# t2_path_template: sub-%1$03d_orig_T2w.nii.gz

simulation_medium: layered

# Parameters differ for each transducer and can be obtained from the manufacturer
transducer:
  - name: right
    n_elements: 10
    Elements_ID_mm: [10.0, 22.1, 29.8, 36.0, 41.4, 46.3, 50.7, 54.9, 58.7, 62.4]
    Elements_OD_mm: [21.1, 28.8, 35.0, 40.4, 45.3, 49.7, 53.9, 57.8, 61.5, 65.0]
    curv_radius_mm: 100
    dist_to_plane_mm: 92.7
    source_amp: 200608
    source_phase_deg: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    source_freq_hz: 300e3
    trans_pos: [186, 209, 189]
    focus_pos: [131, 185, 171]

  - name: left
    n_elements: 10
    Elements_ID_mm: [10.0, 22.1, 29.8, 36.0, 41.4, 46.3, 50.7, 54.9, 58.7, 62.4]
    Elements_OD_mm: [21.1, 28.8, 35.0, 40.4, 45.3, 49.7, 53.9, 57.8, 61.5, 65.0]
    curv_radius_mm: 100
    dist_to_plane_mm: 92.7
    source_amp: 200608
    source_phase_deg: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    source_freq_hz: 300e3
    trans_pos: [42, 213, 189]
    focus_pos: [131, 185, 171]

# Should output be ordered based on subject id?
subject_subfolder: 1

# Optional affix for result files names
results_filename_affix: 'tmp_test_n-transducers'

# Grid resolution (must be isotropic)
grid_step_mm: 0.9  # [mm]
