data_path: /home/.../Ernie_T1_T2/ # the folder with either a) t1 & t2 images, or b) t1 image and the segmentation results, e.g., Ernie subject from SimNIBS
simnibs_bin_path: /home/.../SimNIBS-4.0/bin/ # change to simnibs install

t1_path_template: ernie_T1.nii.gz # path to T1 relative to data_path; all string substitutions will be done using subject_id
t2_path_template: ernie_T2.nii.gz # path to T2 relative to data_path; all string substitutions will be done using subject_id

# If you encounter the error "The qform and sform of do not match. Please run charm with the --forceqform option" when running charm, you can set this to 1 to do it for all subjects
use_forceqform: 0

transducer: 
  array_shape:
    type: annular # 'annular' (Annular array transducer) or 'matrix' (Matrix array transducer)
    
    annular:
      n_elements: 4 # number of elements in the transducer
      Elements_ID_mm: [0, 32.9184, 46.1264, 56.0324]
      Elements_OD_mm: [32.3596, 45.5676, 55.5244, 64.008]
      curv_radius_mm: 63.20 # radius of curvature of the bowl 
      dist_to_plane_mm: 52.38 # distance to the transducer plane from the geometric focus
      source_phase_deg: [0, 0, 0, 274] # original: [0.0, 13.2, 26.4, 52.8] # source phase [deg] (calibrated values at 20 W/cm^2 free-water Isppa)
 
     matrix:
      steering: 3D # 1D (Axial steering) or 3D (Volumetric steering)
      
      # Element shape options:
      #   rect → Rectangular
      #   disc → Circular disc
      #   bowl → Curved (bowl-shaped)
      element_shape: bowl
      
      # Element area is based on a rectangular shape with the specified height and width.
      # If a disc or bowl shape is selected, its area matches that of the rectangular element.
      elem_height_mm: 5.317e-3 # [mm]
      elem_width_mm: 5.317e-3 # [mm]
  
      outer_diameter_mm: 62.5 # outer diameter of the transducer [mm]
      
      # Used only for visualization if element positions are loaded from file.
      is_curved: true
      curved:
        curv_radius_mm: 100 # radius of curvature of the bowl 
        dist_to_plane_mm: 94.99 # distance to the transducer plane from the geometric focus

      # When the Clover setup is enabled, the defined transducer is replicated
      # into a three-leaf Clover configuration (up to three leaves).
      # The parent ROC of the composite setup can differ from the individual transducer ROC.      
      is_clover_setup: true
      clover:
        n_leaves: 2 # Number of leaves (up to three leaves)
        ROC_parent: 100 # [mm]
            
      matrix_shape:
        type: extract_from_file # 'define_here', 'extract_from_file'
        define_here:
          # Type of element grid distribution:
          #   rect → Rectangular grid
          #   fibonacci → Fibonacci grid
          grid_shape: 
            type: fibonacci
             
            rect:
              # Number of rows and columns in the transducer (for rectangular grid).
              n_elem_row: 9
              n_elem_col: 9
              
              # Element spacing in each direction [mm].
              elem_spacing_height_mm: 0.5
              elem_spacing_width_mm: 0.5
              
              sparsity_factor: 1 # (0.1 to 1.0) Example: 0.7 = use 70% of elements

            fibonacci:
              # Total number of elements for Fibonacci grid.
              n_elements: 64   

        extract_from_file:
          file_path: tr2Clover_R100_106.xlsx # Path to the file containing x, y, z coordinates of the elements
          
          # First row and column containing x, y, z element coordinates.
          # Note: MATLAB may ignore the first Excel row if it contains headers.
          start_row: 3
          start_col: 2
          
          # Total number of elements to extract.
          # Set to the full number of elements if you plan to select a random subset later.
          n_elements: 52
          
          # Enable to randomly select a subset of elements from the total.
          select_random_subset: false
          subset:
            # If true, a new random subset is generated each run.
            # If false, the same subset is used for repeatability.
            random_seed: true
            subset_n_elements: 64 # Number of elements to include in the subset.

          # Optionally project the current element layout onto a new radius of curvature (ROC).
          # Note: results may become unrealistic or unfeasible when, for example, spacing between elements decreases with an increasing ROC.
          project_on_new_ROC: false 
            new_ROC_mm: 100 # [mm]
  
  depth_mm: 16 # depth of transducer used for visualization purposes 
  source_amp: 91590 # [Pa]
  source_freq_hz: 250e3 # [Hz] the central frequency
  trans_pos: [128, 139, 15] # position on T1 grid 
  focus_pos: [128, 142, 75] # stimulation target on T1 grid

default_grid_dims: [144, 144, 256]

thermal:
  pd: 0.3
  pri: 0.6  
  ptd: 0.6
  pt_timestep: 0.1
  ptri: 1.2
  ptrd: 14.4
  post_ptri_dur: 15
  post_pt_timestep: 1
  equal_step_duration: 0