function [results_thermal] = thermal_analysis(parameters, results_heating, ...
    time_status_seq, medium_masks, highlighted_pos, segmentation)

    % Process results of thermal simulation
    % Provide time plot of heating
    % Save key values in output table

    disp('Processing the results of thermal simulations...')

    if numel(parameters.transducer) > 1
        warning(['***************************************************\n' ...
            '*  MULTI-TRANSDUCER HEATING RESULTS — READ CAREFULLY\n' ...
            '*\n' ...
            '*  Thermal diffusion is simulated for the COMBINED field,\n' ...
            '*  but ALL focal-plane / time-course heating plots reflect\n' ...
            '*  ONLY first transducer and MAY MISS HOTSPOTS near other beams\n' ...
            '*\n' ...
            '*  DO NOT use these 1D/2D plots as a complete safety check\n' ...
            '*\n' ...
            '*  ALWAYS inspect 3D maxT and CEM43 volumes (NIfTIs)\n' ...
            '***************************************************'])
    end

    % Sets up an empty medium mask if none is specified
    if isempty(medium_masks)
        medium_masks = zeros(parameters.grid.dims);
    end

    % Get tissue-specific masks
    mask = tissuemask_binary(parameters, medium_masks);

    % Creates an output table for temperature readings
    results_thermal = readtable(parameters.io.filename_output_table);

    results_thermal.maxT = max(results_heating.maxT, [], 'all');
    results_thermal.endT = max(results_heating.heating_endT, [], 'all');
    results_thermal.maxCEM43 = max(results_heating.CEM43, [], 'all');
    results_thermal.maxCEM43end = max(results_heating.CEM43_end, [], 'all');

    % Encode layer-specific estimates
    if contains(parameters.simulation.medium, {'layered'; 'phantom'})
        % temperature maximum
        results_thermal.maxT_brain = masked_max_3d(results_heating.maxT, mask.brain);
        results_thermal.maxT_skull = masked_max_3d(results_heating.maxT, mask.skull); 
        results_thermal.maxT_skin = masked_max_3d(results_heating.maxT, mask.skin);
        % temperature (at simulation offset)
        results_thermal.endT_brain = masked_max_3d(results_heating.heating_endT, mask.brain);
        results_thermal.endT_skull = masked_max_3d(results_heating.heating_endT, mask.skull); 
        results_thermal.endT_skin = masked_max_3d(results_heating.heating_endT, mask.skin);
        % temperature rise
        results_thermal.riseT_brain = masked_max_3d(results_heating.maxT, mask.brain)-parameters.thermal.temp_0.brain;
        results_thermal.riseT_skull = masked_max_3d(results_heating.maxT, mask.skull)-parameters.thermal.temp_0.skull; 
        results_thermal.riseT_skin = masked_max_3d(results_heating.maxT, mask.skin)-parameters.thermal.temp_0.skin;
        % temperature rise (at simulation offset)
        results_thermal.rise_endT_brain = results_thermal.endT_brain-parameters.thermal.temp_0.brain;
        results_thermal.rise_endT_skull = results_thermal.endT_skull-parameters.thermal.temp_0.skull; 
        results_thermal.rise_endT_skin = results_thermal.endT_skin-parameters.thermal.temp_0.skin;
        % CEM43
        results_thermal.CEM43_brain = masked_max_3d(results_heating.CEM43, mask.brain);
        results_thermal.CEM43_skull = masked_max_3d(results_heating.CEM43, mask.skull); 
        results_thermal.CEM43_skin = masked_max_3d(results_heating.CEM43, mask.skin);
        % CEM43 (at simulation offset)
        results_thermal.CEM43_end_brain = masked_max_3d(results_heating.CEM43_end, mask.brain);
        results_thermal.CEM43_end_skull = masked_max_3d(results_heating.CEM43_end, mask.skull); 
        results_thermal.CEM43_end_skin = masked_max_3d(results_heating.CEM43_end, mask.skin);
    end
    
    % Save overview table
    writetable(results_thermal, parameters.io.filename_output_table);

    % Creates a visual overlay of the transducer (if 3D T1 image is available)
    if exist('planimg') && isfield(planimg, 't1_header')
        grid.resolution_mm = planimg.t1_header.PixelDimensions(1);
        [~, source_labels] = transducer_setup(...
            parameters.transducer(1), ...
            parameters.transducer(1).trans_pos, ...
            parameters.transducer(1).focus_pos, ...
            size(segmentation), ...
            grid.resolution_mm);
    else
        source_labels = zeros(size(segmentation));
    end

    % Creates a line graph of heating in the focal plane and (OPTIONAL) video of the heat propagation
    thermal_plot_sim(...
        results_heating.focal_planeT, ...
        time_status_seq, ...
        parameters, ...
        parameters.transducer(1).trans_pos, ...
        medium_masks, ...
        results_heating.focal_planeCEM43, ...
        results_heating.timeseries);
            
    % Plots the maximum temperature in the segmented brain
    if results_thermal.maxT < 38
        temp_color_range = [37, 38];
    else
        temp_color_range = [37, results_thermal.maxT];
    end

    % plot heating superimposed on segmentation
    if ndims(results_heating.maxT) == 3

        slices = struct( ...
            'dim', {'x', 'y', 'z'}, ...
            'pos', {parameters.transducer(1).focus_pos(1), ...
            parameters.transducer(1).focus_pos(2), ...
            parameters.transducer(1).focus_pos(3)});

        for i = 1:numel(slices)
            slice = slices(i);
            [~,~,~,~,~,~,~,h]=plot_overlay(...
                results_heating.maxT, ...
                segmentation, ...
                source_labels, ...
                parameters, ...
                {slice.dim, slice.pos}, ...
                parameters.transducer(1).trans_pos, ...
                parameters.transducer(1).focus_pos, ...
                highlighted_pos, ...
                'overlay_color_range', temp_color_range);

            % Construct output filename
            output_plot_filename = fullfile(parameters.io.output_dir,...
                sprintf('sub-%03d_%s_maxT_%s%s.png',...
                parameters.subject_id, ...
                parameters.simulation.medium, ...
                slice.dim, ...
                parameters.io.output_affix));

            saveas(h, output_plot_filename, 'png')
            close(h);
        end
    elseif ndims(results_heating.maxT) == 2
        [h]=plot_overlay_2d(...
                results_heating.maxT, ...
                medium_masks, ...
                source_labels, ...
                after_exit_plane_mask, ...
                parameters.transducer(1).trans_pos, ...
                parameters.transducer(1).focus_pos, ...
                highlighted_pos, ...
                'overlay_color_range', temp_color_range, ...
                'bg_bw_range', [0, numel(fieldnames(parameters.layers))]);

        output_plot_filename = fullfile(parameters.io.output_dir,...
            sprintf('sub-%03d_%s_maxT%s.png',...
            parameters.subject_id, ...
            parameters.simulation.medium, ...
            parameters.io.output_affix));
        saveas(h, output_plot_filename, 'png')
        close(h);
    end
