function [results_thermal] = thermal_analysis(parameters, results_heating, ...
    time_status_seq, medium_masks, highlighted_pos, segmentation)

    % Process results of thermal simulation
    % Provide time plot of heating
    % Save key values in output table

    disp('Processing the results of thermal simulations...')

    if numel(parameters.transducer) > 1
        warning(['***************************************************\n' ...
            '*  MULTI-TRANSDUCER HEATING RESULTS — READ CAREFULLY\n' ...
            '*\n' ...
            '*  Thermal diffusion is simulated for the COMBINED field,\n' ...
            '*  but ALL focal-plane / time-course heating plots reflect\n' ...
            '*  ONLY first transducer and MAY MISS HOTSPOTS near other beams\n' ...
            '*\n' ...
            '*  DO NOT use these 1D/2D plots as a complete safety check\n' ...
            '*\n' ...
            '*  ALWAYS inspect 3D maxT and CEM43 volumes (NIfTIs)\n' ...
            '***************************************************'])
    end

    % Sets up an empty medium mask if none is specified
    if isempty(medium_masks)
        medium_masks = zeros(parameters.grid_dims);
    end

    % Get tissue-specific masks
    mask = tissuemask_binary(parameters, medium_masks);

    % Creates an output table for temperature readings
    results_thermal = readtable(parameters.filename_output_table);

    results_thermal.maxT = max(results_heating.maxT, [], 'all');
    results_thermal.maxCEM43 = max(results_heating.CEM43, [], 'all');
    % Overwrites the max temperature by dividing it up for each layer
    % in case a layered simulation_medium was selected
    if contains(parameters.simulation_medium, {'layered'; 'phantom'})
        results_thermal.maxT_brain = masked_max_3d(results_heating.maxT, mask.brain);
        results_thermal.maxT_skull = masked_max_3d(results_heating.maxT, mask.skull); 
        results_thermal.maxT_skin = masked_max_3d(results_heating.maxT, mask.skin);
        results_thermal.riseT_brain = masked_max_3d(results_heating.maxT, mask.brain)-parameters.thermal.temp_0.brain;
        results_thermal.riseT_skull = masked_max_3d(results_heating.maxT, mask.skull)-parameters.thermal.temp_0.skull; 
        results_thermal.riseT_skin = masked_max_3d(results_heating.maxT, mask.skin)-parameters.thermal.temp_0.skin;
        results_thermal.CEM43_brain = masked_max_3d(results_heating.CEM43, mask.brain);
        results_thermal.CEM43_skull = masked_max_3d(results_heating.CEM43, mask.skull); 
        results_thermal.CEM43_skin = masked_max_3d(results_heating.CEM43, mask.skin);
    end
    writetable(results_thermal, parameters.filename_output_table);

    % Creates a visual overlay of the transducer (if 3D T1 image is available)
    if exist('planimg') && isfield(planimg, 't1_header')
        grid_step_mm = planimg.t1_header.PixelDimensions(1);
        [~, source_labels] = transducer_setup(...
            parameters.transducer(1), ...
            parameters.transducer(1).trans_pos, ...
            parameters.transducer(1).focus_pos, ...
            size(segmentation), ...
            grid_step_mm);
    else
        source_labels = zeros(size(segmentation));
    end

    % Creates a line graph and (OPTIONAL) video of the heat propagation
    thermal_plot_sim(...
        results_heating.focal_planeT, ...
        time_status_seq, ...
        parameters, ...
        parameters.transducer(1).trans_pos, ...
        medium_masks, ...
        results_heating.focal_planeCEM43);
            
    % Plots the maximum temperature in the segmented brain
    if results_thermal.maxT < 38
        temp_color_range = [37, 38];
    else
        temp_color_range = [37, results_thermal.maxT];
    end

    % plot heating superimposed on segmentation
    if ndims(results_heating.maxT) == 3
        [~,~,~,~,~,~,~,h]=plot_overlay(...
                results_heating.maxT, ...
                segmentation, ...
                source_labels, ...
                parameters, ...
                {'y', parameters.transducer(1).focus_pos(2)}, ...
                parameters.transducer(1).trans_pos, ...
                parameters.transducer(1).focus_pos, ...
                highlighted_pos, ...
                'overlay_color_range', temp_color_range);
    elseif ndims(results_heating.maxT) == 2
        [h]=plot_overlay_2d(...
                results_heating.maxT, ...
                medium_masks, ...
                source_labels, ...
                after_exit_plane_mask, ...
                parameters.transducer(1).trans_pos, ...
                parameters.transducer(1).focus_pos, ...
                highlighted_pos, ...
                'overlay_color_range', temp_color_range, ...
                'bg_bw_range', [0, numel(fieldnames(parameters.layers))]);
    end
    output_plot_filename = fullfile(parameters.output_dir,...
        sprintf('sub-%03d_%s_maxT%s.png',...
        parameters.subject_id, parameters.simulation_medium, parameters.results_filename_affix));
    saveas(h, output_plot_filename, 'png')
    close(h);