function css = css_styles_base()
% CSS_STYLES_BASE  Shared design system for all PRESTUS HTML reports.
%
% Returns a character array with the complete CSS for the "precision
% scientific instrument" report design: a light "paper instrument" theme and
% a dark "control room" theme (selected via the data-theme attribute on
% <html>), with acoustic content keyed cool/blue and thermal content keyed
% warm. All colours are CSS variables so dark mode is a single attribute flip.
% Both the per-subject and group reports share this one stylesheet; the
% per-report css_styles helpers simply return this function.
%
% Use as:
%   css = css_styles_base()
%
% See also: GENERATE_SIMULATION_REPORT, GENERATE_GROUP_REPORT, REPORT_SCRIPTS
css = [...
'/* ===== design tokens ===== */' newline ...
':root{' ...
'--font-display:"Fraunces","Spectral",Georgia,"Times New Roman",serif;' ...
'--font-sans:"Spline Sans",system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;' ...
'--font-mono:"Spline Sans Mono","JetBrains Mono",ui-monospace,"SF Mono",Menlo,Consolas,monospace;' ...
'--bg:#e9edf1;--bg2:#dfe5ec;--surface:#fff;--surface-2:#f5f7fa;--surface-3:#eef2f6;' ...
'--ink:#10161d;--ink-2:#3d4956;--ink-3:#6b7886;--ink-4:#9aa7b4;--line:#dde3ea;--line-2:#cdd6df;' ...
'--shadow:0 1px 2px rgba(16,22,29,.06),0 8px 24px -12px rgba(16,22,29,.18);' ...
'--shadow-lg:0 24px 60px -24px rgba(16,22,29,.35);' ...
'--green:#1f9d57;--green-bg:#e8f7ee;--amber:#d98a1f;--amber-bg:#fdf3e0;--red:#d63b3b;--red-bg:#fcebeb;' ...
'--gray:#94a3b2;--gray-bg:#f1f4f7;--info:#2f7fd1;--info-bg:#e9f2fb;' ...
'--acoustic:#1f6fb2;--acoustic-soft:#e7f1f9;--thermal:#d9482a;--thermal-soft:#fceee9;' ...
'--radius:14px;--radius-sm:9px;}' newline ...
'html[data-theme="dark"]{' ...
'--bg:#0a0e13;--bg2:#0d1219;--surface:#141b24;--surface-2:#1b2531;--surface-3:#212d3b;' ...
'--ink:#e9eff5;--ink-2:#aebdcc;--ink-3:#7d8c9d;--ink-4:#5a6776;--line:#243140;--line-2:#2e3d4e;' ...
'--shadow:0 1px 2px rgba(0,0,0,.4),0 12px 32px -14px rgba(0,0,0,.7);' ...
'--shadow-lg:0 30px 70px -20px rgba(0,0,0,.85);' ...
'--green:#3cd07f;--green-bg:#0f2a1c;--amber:#f0ac4a;--amber-bg:#2c2110;--red:#ff6b6b;--red-bg:#2e1414;' ...
'--gray:#64748b;--gray-bg:#1a232e;--info:#5aa9ef;--info-bg:#10243a;' ...
'--acoustic:#5aa9ef;--acoustic-soft:#10243a;--thermal:#ff7a52;--thermal-soft:#2a1610;}' newline ...
'*{box-sizing:border-box;margin:0;padding:0}' newline ...
'html{scroll-behavior:smooth;scroll-padding-top:84px}' newline ...
'body{font-family:var(--font-sans);background:var(--bg);color:var(--ink);line-height:1.6;' ...
'-webkit-font-smoothing:antialiased;max-width:1240px;margin:0 auto;padding:20px;' ...
'background-image:radial-gradient(1200px 600px at 80% -10%,var(--bg2),transparent 60%);background-attachment:fixed}' newline ...
'h1{font-family:var(--font-display);font-weight:600;font-size:2.2rem;line-height:1.06;letter-spacing:-.01em;margin-bottom:.18em}' newline ...
'h2{font-family:var(--font-display);font-weight:600;font-size:1.3rem;color:var(--ink);margin-bottom:.7em}' newline ...
'h3{font-family:var(--font-display);font-size:1.05rem;font-weight:600;color:var(--ink-2);margin:16px 0 8px}' newline ...
'a{color:var(--acoustic)}' newline ...
'mark{background:var(--amber);color:#1a1205;border-radius:2px;padding:0 2px}' newline ...
'/* ===== section shells ===== */' newline ...
'.report-section{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);' ...
'padding:24px 26px;margin-bottom:18px;box-shadow:var(--shadow);position:relative}' newline ...
'.error-section{border-left:4px solid var(--red)}' newline ...
'.error-notice{color:var(--red);font-style:italic}' newline ...
'/* ===== top bar / nav ===== */' newline ...
'.toc{position:sticky;top:0;z-index:100;background:color-mix(in srgb,var(--surface) 86%,transparent);' ...
'backdrop-filter:saturate(1.4) blur(10px);border:1px solid var(--line);border-radius:12px;' ...
'padding:9px 14px;margin-bottom:18px;display:flex;align-items:center;gap:8px;flex-wrap:wrap}' newline ...
'.toc strong{font-family:var(--font-display);margin-right:4px}' newline ...
'.toc a{text-decoration:none;color:var(--ink-3);font-size:.82rem;font-weight:500;padding:5px 10px;border-radius:8px;white-space:nowrap;transition:.15s}' newline ...
'.toc a:hover{color:var(--ink);background:var(--surface-2)}' newline ...
'.toc a.active{color:var(--acoustic);background:var(--acoustic-soft)}' newline ...
'.toc-spacer{flex:1}' newline ...
'.toc-status{width:10px;height:10px;border-radius:50%;flex-shrink:0;box-shadow:0 0 0 3px color-mix(in srgb,currentColor 18%,transparent)}' newline ...
'/* brand + tools */' newline ...
'.brand{display:flex;align-items:center;gap:10px;text-decoration:none;color:var(--ink)}' newline ...
'.brand img{height:30px;width:auto;display:block}' newline ...
'.brand .mark{flex-shrink:0}' newline ...
'.brand .wm{font-family:var(--font-display);font-weight:600;font-size:1.08rem;letter-spacing:.01em;line-height:1}' newline ...
'.brand .wm b{color:var(--acoustic)}' newline ...
'.brand small{display:block;font-size:.58rem;letter-spacing:.3em;text-transform:uppercase;color:var(--ink-3);margin-top:1px}' newline ...
'.theme-btn{display:grid;place-items:center;width:34px;height:34px;border-radius:9px;border:1px solid var(--line);' ...
'background:var(--surface-2);color:var(--ink-2);cursor:pointer;transition:.2s;flex-shrink:0}' newline ...
'.theme-btn:hover{color:var(--ink);border-color:var(--line-2)}' newline ...
'.report-search{display:flex;align-items:center;gap:7px;background:var(--surface-2);border:1px solid var(--line);' ...
'border-radius:9px;padding:5px 10px;width:150px;transition:.2s}' newline ...
'.report-search:focus-within{width:185px;border-color:var(--acoustic)}' newline ...
'.report-search input{border:0;background:transparent;outline:0;color:var(--ink);font-family:var(--font-sans);font-size:.82rem;width:100%}' newline ...
'.report-search svg{flex-shrink:0;color:var(--ink-3)}' newline ...
'/* ===== verdict banner ===== */' newline ...
'.verdict{margin:18px 0;border-radius:var(--radius);overflow:hidden;background:var(--surface);box-shadow:var(--shadow);' ...
'border:1px solid var(--line);display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:20px;padding:18px 22px;position:relative}' newline ...
'.verdict::before{content:"";position:absolute;left:0;top:0;bottom:0;width:6px}' newline ...
'.verdict.pass::before{background:var(--green)}.verdict.fail::before{background:var(--red)}' newline ...
'.verdict .glyph{width:50px;height:50px;border-radius:13px;display:grid;place-items:center;flex-shrink:0}' newline ...
'.verdict.pass .glyph{background:var(--green-bg);color:var(--green)}' newline ...
'.verdict.fail .glyph{background:var(--red-bg);color:var(--red)}' newline ...
'.verdict .glyph svg{width:28px;height:28px}' newline ...
'.verdict h2{font-size:1.4rem;border:0;margin:0;padding:0}' newline ...
'.verdict p{color:var(--ink-3);font-size:.86rem;margin-top:2px}' newline ...
'.verdict .exsub{margin-top:8px;display:flex;flex-wrap:wrap;gap:6px}' newline ...
'.exbadge{font-family:var(--font-mono);font-size:.73rem;font-weight:600;color:var(--red);background:var(--red-bg);' ...
'border:1px solid color-mix(in srgb,var(--red) 30%,transparent);padding:3px 9px;border-radius:999px;text-decoration:none}' newline ...
'.tally{display:flex;gap:9px}' newline ...
'.tally .t{text-align:center;min-width:62px;padding:8px 10px;border-radius:10px;background:var(--surface-2);border:1px solid var(--line)}' newline ...
'.tally .t .n{font-family:var(--font-mono);font-weight:700;font-size:1.3rem;line-height:1}' newline ...
'.tally .t .l{font-size:.6rem;letter-spacing:.1em;text-transform:uppercase;color:var(--ink-3);margin-top:3px}' newline ...
'.tally .t.g .n{color:var(--green)}.tally .t.a .n{color:var(--amber)}.tally .t.r .n{color:var(--red)}.tally .t.b .n{color:var(--acoustic)}' newline ...
'/* ===== safety dashboard ===== */' newline ...
'.dash-group-label{display:flex;align-items:center;gap:10px;margin:16px 0 11px}' newline ...
'.dash-group-label .dot{width:9px;height:9px;border-radius:3px}' newline ...
'.dash-group-label.ac .dot{background:var(--acoustic)}.dash-group-label.th .dot{background:var(--thermal)}' ...
'.dash-group-label.mech .dot{background:var(--acoustic)}.dash-group-label.other .dot{background:var(--ink-4)}' newline ...
'.dash-group-label .t{font-size:.73rem;font-weight:700;letter-spacing:.16em;text-transform:uppercase;color:var(--ink-2)}' newline ...
'.dash-group-label .s{font-size:.73rem;color:var(--ink-4)}' newline ...
'.safety-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(186px,1fr));gap:12px;margin-bottom:8px}' newline ...
'.safety-card{position:relative;border:1px solid var(--line);border-radius:var(--radius-sm);padding:14px 14px 13px;' ...
'background:var(--surface-2);transition:transform .2s,box-shadow .2s}' newline ...
'.safety-card:hover{transform:translateY(-2px);box-shadow:var(--shadow);border-color:var(--line-2)}' newline ...
'.safety-card::before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;border-radius:var(--radius-sm) 0 0 var(--radius-sm)}' newline ...
'.safety-green::before{background:var(--green)}.safety-amber::before{background:var(--amber)}' ...
'.safety-red::before{background:var(--red)}.safety-gray::before{background:var(--gray)}.safety-info::before{background:var(--info)}' newline ...
'.safety-label{font-size:.71rem;letter-spacing:.05em;text-transform:uppercase;color:var(--ink-3);font-weight:600;' ...
'display:flex;align-items:center;gap:6px;justify-content:space-between}' newline ...
'.safety-value{font-family:var(--font-mono);font-weight:700;font-size:1.55rem;margin:7px 0 2px;letter-spacing:-.01em}' newline ...
'.safety-green .safety-value{color:var(--green)}.safety-amber .safety-value{color:var(--amber)}' ...
'.safety-red .safety-value{color:var(--red)}.safety-info .safety-value{color:var(--info)}.safety-gray .safety-value{color:var(--ink-3)}' newline ...
'.risk-limit{font-size:.71rem;color:var(--ink-4);font-family:var(--font-mono)}' newline ...
'.safety-flag{display:inline-flex;align-items:center;gap:4px;font-size:.6rem;font-weight:700;letter-spacing:.06em;' ...
'text-transform:uppercase;color:#fff;background:var(--red);padding:2px 7px;border-radius:999px}' newline ...
'.safety-card.flagged{box-shadow:0 0 0 2px var(--red) inset}' newline ...
'.safety-q{width:15px;height:15px;border-radius:50%;border:1px solid var(--line-2);color:var(--ink-4);font-size:.64rem;' ...
'display:grid;place-items:center;cursor:help;flex-shrink:0}' newline ...
'/* meter with limit tick */' newline ...
'.safety-bar-track{position:relative;height:5px;background:var(--surface-3);border-radius:3px;margin-top:9px;overflow:visible}' newline ...
'.safety-bar{height:100%;border-radius:3px;position:absolute;left:0;top:0;transition:width 1s cubic-bezier(.2,.7,.2,1)}' newline ...
'.safety-green .safety-bar{background:var(--green)}.safety-amber .safety-bar{background:var(--amber)}' ...
'.safety-red .safety-bar{background:var(--red)}.safety-info .safety-bar{background:var(--info)}.safety-gray .safety-bar{background:var(--gray)}' newline ...
'.safety-bar-limit{position:absolute;top:-3px;bottom:-3px;width:2px;background:var(--ink-4);opacity:.6;transform:translateX(-50%)}' newline ...
'.safety-bar-range{font-size:.72rem;color:var(--ink-4);margin-top:6px}' newline ...
'.safety-bar-marker{position:absolute;top:-4px;width:9px;height:9px;border-radius:50%;background:var(--ink);transform:translateX(-50%);z-index:2;border:2px solid var(--surface-2)}' newline ...
'.safety-bar-marker--default{background:var(--ink)}' newline ...
'.safety-sd{font-size:.76rem;color:var(--ink-3);margin:2px 0;font-family:var(--font-mono)}' newline ...
'.safety-range{font-size:.76rem;color:var(--ink-4);margin-bottom:4px;font-family:var(--font-mono)}' newline ...
'.safety-footnote{font-size:.77rem;color:var(--ink-4);margin-top:13px;line-height:1.55}' newline ...
'.safety-footnote a{color:var(--ink-3);text-decoration:none;border-bottom:1px dotted var(--ink-4)}' newline ...
'.safety-footnote a:hover{color:var(--ink-2)}' newline ...
'/* tooltip */' newline ...
'.tip{position:relative}' newline ...
'.tip .tip-pop{position:absolute;bottom:calc(100% + 9px);left:50%;transform:translateX(-50%) translateY(4px);' ...
'background:var(--ink);color:var(--surface);padding:10px 12px;border-radius:9px;width:225px;font-size:.75rem;line-height:1.45;' ...
'opacity:0;visibility:hidden;transition:.18s;z-index:50;box-shadow:var(--shadow-lg);pointer-events:none;font-family:var(--font-sans);text-transform:none;letter-spacing:normal;font-weight:400}' newline ...
'.tip .tip-pop::after{content:"";position:absolute;top:100%;left:50%;transform:translateX(-50%);border:6px solid transparent;border-top-color:var(--ink)}' newline ...
'.tip:hover .tip-pop{opacity:1;visibility:visible;transform:translateX(-50%) translateY(0)}' newline ...
'.tip .tip-pop .lh{display:block;color:var(--info);font-family:var(--font-mono);font-size:.71rem;margin-top:5px}' newline ...
'.tip .tip-pop b{color:#fff}' newline ...
'/* ===== summary stat cards ===== */' newline ...
'.summary-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(152px,1fr));gap:12px}' newline ...
'.summary-card{background:linear-gradient(180deg,var(--surface-2),var(--surface));border:1px solid var(--line);' ...
'border-radius:var(--radius-sm);padding:15px 16px}' newline ...
'.summary-label{font-size:.71rem;color:var(--ink-3);text-transform:uppercase;letter-spacing:.05em;font-weight:600;margin-bottom:4px}' newline ...
'.summary-value{font-family:var(--font-mono);font-size:1.45rem;font-weight:700;color:var(--ink)}' newline ...
'.summary-unit{font-size:.72rem;color:var(--ink-4);margin-top:2px}' newline ...
'.summary-note{font-size:.69rem;color:var(--ink-4);margin-top:3px}' newline ...
'.summary-card.hi{background:var(--acoustic-soft);border-color:transparent}.summary-card.hi .summary-value{color:var(--acoustic)}' newline ...
'/* ===== tables ===== */' newline ...
'.info-table,.config-table{border-collapse:collapse;width:100%}' newline ...
'.info-table th,.config-table th{text-align:left;padding:5px 16px 5px 0;color:var(--ink-3);font-weight:500;white-space:nowrap;vertical-align:top}' newline ...
'.info-table td,.config-table td{padding:5px 0;font-family:var(--font-mono);color:var(--ink)}' newline ...
'.table-wrapper{overflow-x:auto;margin:12px 0;border:1px solid var(--line);border-radius:var(--radius-sm);-webkit-overflow-scrolling:touch}' newline ...
'.data-table{width:100%;border-collapse:collapse;font-size:.86rem}' newline ...
'.data-table thead{background:var(--surface-3)}' newline ...
'.data-table th,.data-table td{padding:8px 12px;text-align:left;border-bottom:1px solid var(--line);white-space:nowrap}' newline ...
'.data-table th{font-weight:600;color:var(--ink-2);font-size:.78rem}' newline ...
'.data-table td{font-family:var(--font-mono);color:var(--ink-2)}' newline ...
'.data-table tbody tr:nth-child(even){background:color-mix(in srgb,var(--surface-2) 60%,transparent)}' newline ...
'.row-green{background:var(--green-bg)}.row-amber{background:var(--amber-bg)}.row-red{background:var(--red-bg);font-weight:600}.row-gray{background:var(--gray-bg);color:var(--ink-4)}' newline ...
'.cell-green{background:var(--green-bg)!important}.cell-amber{background:var(--amber-bg)!important}' ...
'.cell-red{background:var(--red-bg)!important;font-weight:600}.cell-gray{background:var(--gray-bg)!important;color:var(--ink-4)}' newline ...
'/* ===== badges ===== */' newline ...
'.badge{display:inline-block;padding:3px 10px;border-radius:999px;font-size:.76rem;font-weight:500;margin-left:6px;border:1px solid var(--line)}' newline ...
'.badge-green{background:var(--green-bg);color:var(--green)}.badge-amber{background:var(--amber-bg);color:var(--amber)}' ...
'.badge-blue{background:var(--acoustic-soft);color:var(--acoustic)}.badge-gray{background:var(--gray-bg);color:var(--ink-3)}' newline ...
'/* ===== banners ===== */' newline ...
'.medium-banner{padding:12px 16px;border-radius:var(--radius-sm);margin-bottom:14px;font-size:.88rem}' newline ...
'.medium-water{background:var(--acoustic-soft);border-left:4px solid var(--info);color:var(--ink-2)}' newline ...
'.medium-layered{background:var(--amber-bg);border-left:4px solid var(--amber);color:var(--ink-2)}' newline ...
'/* ===== collapsibles ===== */' newline ...
'details.report-section{padding:0}' newline ...
'details.report-section>summary{cursor:pointer;list-style:none;padding:16px 24px;display:flex;align-items:center;gap:10px}' newline ...
'details.report-section>summary::-webkit-details-marker{display:none}' newline ...
'details.report-section>summary::before{content:"";width:8px;height:8px;border-right:2px solid var(--ink-3);' ...
'border-bottom:2px solid var(--ink-3);transform:rotate(-45deg);transition:transform .2s;flex-shrink:0;margin-left:2px}' newline ...
'details[open].report-section>summary::before{transform:rotate(45deg)}' newline ...
'details.report-section>summary h2{margin:0}' newline ...
'details.report-section>summary .hint{font-size:.78rem;color:var(--ink-4);margin-left:auto}' newline ...
'details.report-section>.section-content{padding:0 24px 24px 24px}' newline ...
'details.subject-card{background:var(--surface-2);border:1px solid var(--line);border-radius:var(--radius-sm);padding:0;margin-bottom:12px}' newline ...
'details.subject-card>summary{cursor:pointer;list-style:none;padding:11px 16px;font-weight:600}' newline ...
'details.subject-card>summary::-webkit-details-marker{display:none}' newline ...
'details.subject-card>summary::before{content:"\25B6";font-size:.7em;margin-right:8px;color:var(--ink-3);transition:transform .2s}' newline ...
'details[open].subject-card>summary::before{transform:rotate(90deg)}' newline ...
'details.subject-card>.section-content{padding:0 16px 16px 16px}' newline ...
'/* ===== images + lightbox ===== */' newline ...
'.image-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(380px,100%),1fr));gap:16px;margin:14px 0}' newline ...
'.image-grid--3col{grid-template-columns:repeat(3,1fr)}' newline ...
'.image-grid--wide{grid-template-columns:repeat(auto-fill,minmax(min(600px,100%),1fr))}' newline ...
'.image-grid--narrow{grid-template-columns:repeat(auto-fill,minmax(min(280px,100%),1fr))}' newline ...
'@media (max-width:700px){.image-grid--3col{grid-template-columns:1fr}}' newline ...
'figure{margin:0;min-width:0;border:1px solid var(--line);border-radius:var(--radius-sm);overflow:hidden;background:var(--surface-2)}' newline ...
'figure img{display:block;width:100%;height:auto;cursor:zoom-in;border-bottom:1px solid var(--line)}' newline ...
'figcaption{font-size:.82rem;color:var(--ink-3);padding:8px 12px;text-align:center}' newline ...
'.placeholder-img{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:120px;' ...
'background:var(--surface-3);border:1px dashed var(--line-2);border-radius:var(--radius-sm);color:var(--ink-4);font-size:.85em;padding:12px;text-align:center}' newline ...
'.lb-overlay{position:fixed;inset:0;background:rgba(6,9,13,.9);backdrop-filter:blur(4px);z-index:1000;' ...
'display:flex;align-items:center;justify-content:center;flex-direction:column;gap:14px;cursor:zoom-out}' newline ...
'.lb-overlay img{max-width:92vw;max-height:82vh;object-fit:contain;border-radius:6px;cursor:default;transition:transform .15s}' newline ...
'.lb-close{position:fixed;top:16px;right:24px;color:#fff;font-size:2em;cursor:pointer;z-index:1001;line-height:1;background:none;border:0}' newline ...
'.lb-ctrls{display:flex;gap:10px}' newline ...
'.lb-ctrls button{background:#1b2531;color:#e9eff5;border:1px solid #2e3d4e;border-radius:8px;padding:7px 13px;cursor:pointer;font-family:var(--font-sans);font-size:.82rem}' newline ...
'.lb-stage{display:flex;gap:14px;align-items:center;justify-content:center;flex-wrap:wrap}' newline ...
'.lb-stage figure{background:#0d1219;border-color:#243140}' newline ...
'figure .cmp{font-size:.7rem;color:var(--acoustic);cursor:pointer;border:1px solid var(--line);padding:2px 8px;border-radius:6px;margin-left:8px}' newline ...
'figure .cmp.on{background:var(--acoustic);color:#fff;border-color:transparent}' newline ...
'/* ===== group: range cards + analysis + roster ===== */' newline ...
'.gcard .gl{display:flex;justify-content:space-between;align-items:baseline;gap:8px}' newline ...
'.an-tabs{display:flex;gap:6px;margin:4px 0 14px;flex-wrap:wrap}' newline ...
'.an-tab{font-size:.82rem;font-weight:600;padding:7px 14px;border-radius:8px;border:1px solid var(--line);background:var(--surface-2);color:var(--ink-3);cursor:pointer}' newline ...
'.an-tab.on{background:var(--acoustic);color:#fff;border-color:transparent}' newline ...
'.an-ctrls{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px}' newline ...
'.an-ctrls label{font-size:.76rem;color:var(--ink-3);display:flex;align-items:center;gap:6px}' newline ...
'select{font-family:var(--font-sans);font-size:.83rem;padding:6px 10px;border-radius:8px;border:1px solid var(--line);background:var(--surface-2);color:var(--ink);outline:0}' newline ...
'.an-plot{background:var(--surface-2);border:1px solid var(--line);border-radius:var(--radius-sm);padding:10px}' newline ...
'.an-plot svg{display:block;width:100%;height:auto;font-family:var(--font-mono)}' newline ...
'.an-legend{display:flex;gap:16px;flex-wrap:wrap;font-size:.74rem;color:var(--ink-3);margin-top:8px}' newline ...
'.an-legend i{display:inline-block;width:10px;height:10px;border-radius:3px;margin-right:5px;vertical-align:middle}' newline ...
'table.roster{width:100%;border-collapse:collapse;font-size:.85rem}' newline ...
'table.roster thead{background:var(--surface-3)}' newline ...
'table.roster th{text-align:right;padding:9px 12px;font-weight:600;color:var(--ink-2);white-space:nowrap;font-size:.76rem;cursor:pointer;user-select:none;border-bottom:1px solid var(--line)}' newline ...
'table.roster th:first-child,table.roster td:first-child{text-align:left}' newline ...
'table.roster th .ar{opacity:.3;font-size:.7rem}' newline ...
'table.roster th.sort .ar{opacity:1;color:var(--acoustic)}' newline ...
'table.roster td{padding:8px 12px;border-top:1px solid var(--line);font-family:var(--font-mono);color:var(--ink-2);white-space:nowrap;text-align:right}' newline ...
'table.roster tr.exceed td:first-child{box-shadow:inset 3px 0 0 var(--red)}' newline ...
'table.roster td.over{color:var(--red);font-weight:700}table.roster td.near{color:var(--amber)}' newline ...
'.roster-flag{font-size:.6rem;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#fff;background:var(--red);padding:2px 6px;border-radius:999px;margin-right:6px}' newline ...
'.rtools{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:12px}' newline ...
'.rtools .toggle{display:inline-flex;align-items:center;gap:7px;font-size:.8rem;color:var(--ink-2);cursor:pointer;background:var(--surface-2);border:1px solid var(--line);border-radius:8px;padding:6px 11px}' newline ...
'.rtools .count{font-size:.78rem;color:var(--ink-4);margin-left:auto;font-family:var(--font-mono)}' newline ...
'/* group filter (legacy) */' newline ...
'.filter-bar{position:sticky;top:62px;z-index:90}' newline ...
'.filter-controls{display:flex;align-items:center;gap:10px;margin:8px 0;flex-wrap:wrap}' newline ...
'.filter-btn{padding:5px 12px;border-radius:8px;border:1px solid var(--line);background:var(--surface-2);color:var(--ink-2);cursor:pointer;font-size:.83rem}' newline ...
'.filter-btn:hover{background:var(--surface-3)}' newline ...
'.filter-hint{font-size:.8rem;color:var(--ink-4)}' newline ...
'.filter-checkboxes{display:flex;flex-wrap:wrap;gap:8px 14px}' newline ...
'.filter-chk{font-size:.84rem;color:var(--ink-2);user-select:none;cursor:pointer}' newline ...
'.filter-chk input{margin-right:4px;vertical-align:middle;accent-color:var(--acoustic)}' newline ...
'/* ===== config dump, log, misc ===== */' newline ...
'.config-dump-bar{display:flex;gap:8px;align-items:center;margin:14px 0 8px}' newline ...
'.config-dump-bar input{flex:1;background:var(--surface-2);border:1px solid var(--line);border-radius:8px;padding:7px 11px;color:var(--ink);font-family:var(--font-mono);font-size:.8rem;outline:0}' newline ...
'pre.config-dump,.log-block{max-height:380px;overflow:auto;background:var(--surface-3);border:1px solid var(--line);' ...
'border-radius:var(--radius-sm);padding:14px 16px;font-family:var(--font-mono);font-size:.78rem;line-height:1.55;color:var(--ink-2);white-space:pre-wrap;word-wrap:break-word}' newline ...
'.boilerplate-license{margin-top:18px;padding:12px 16px;background:var(--surface-2);border-left:3px solid var(--ink-4);border-radius:6px;font-size:.82em;color:var(--ink-3)}' newline ...
'.timing-table{margin:12px 0;font-size:.9em}.timing-table td:first-child{white-space:nowrap}' newline ...
'.placeholder{color:var(--ink-4);font-style:italic}' newline ...
'.note{font-size:.85rem;color:var(--ink-3);margin:8px 0}' newline ...
'code{background:var(--surface-3);padding:2px 6px;border-radius:3px;font-size:.9em;font-family:var(--font-mono)}' newline ...
'footer{text-align:center;color:var(--ink-4);font-size:.8rem;padding:26px 0 8px}' newline ...
'/* entrance animation */' newline ...
'@keyframes prestus-rise{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}' newline ...
'.anim{animation:prestus-rise .55s both}' newline ...
'/* responsive + print */' newline ...
'@media (max-width:760px){h1{font-size:1.7rem}.verdict{grid-template-columns:1fr}.toc .hide-sm{display:none}}' newline ...
'@media print{html{scroll-behavior:auto}body{background:#fff;max-width:none}' ...
'.report-section{box-shadow:none;border:1px solid #ccc;break-inside:avoid}' ...
'.toc,.theme-btn,.report-search,.lb-overlay,.safety-q,.rtools{display:none}' ...
'details{display:block}details>summary{display:none}details>.section-content{padding:0 24px 24px!important}' ...
'.log-block,pre.config-dump{max-height:none}figure{break-inside:avoid}.safety-grid{break-inside:avoid}' ...
'figure img{cursor:default}.image-grid{grid-template-columns:repeat(2,1fr)}.image-grid--wide{grid-template-columns:1fr}}' newline ...
];
end
