function css = css_styles_base()
% CSS_STYLES_BASE  CSS rules common to all PRESTUS HTML reports.
% Each per-report css_styles() calls this function and appends its own rules.
css = [...
':root { --green: #22c55e; --amber: #f59e0b; --red: #ef4444; --gray: #9ca3af; --info: #3b82f6; }' newline ...
'html { scroll-behavior: smooth; scroll-padding-top: 60px; }' newline ...
'* { box-sizing: border-box; margin: 0; padding: 0; }' newline ...
'body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; ' ...
  'max-width: 1200px; margin: 0 auto; padding: 20px; background: #f8fafc; color: #1e293b; line-height: 1.6; }' newline ...
'h1 { font-size: 1.8em; margin-bottom: 0.3em; }' newline ...
'h2 { font-size: 1.3em; margin-bottom: 0.8em; color: #334155; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.3em; }' newline ...
'h3 { font-size: 1.05em; margin: 16px 0 8px; color: #475569; }' newline ...
'.report-section { background: white; border-radius: 8px; padding: 24px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }' newline ...
'.error-section { border-left: 4px solid var(--red); }' newline ...
'.error-notice { color: var(--red); font-style: italic; }' newline ...
newline ...
'/* Safety dashboard */' newline ...
'.safety-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(175px, 1fr)); gap: 12px; margin-bottom: 12px; }' newline ...
'.safety-card { padding: 14px; border-radius: 6px; }' newline ...
'.safety-green  { border-left: 4px solid var(--green); background: #f0fdf4; }' newline ...
'.safety-amber  { border-left: 4px solid var(--amber); background: #fffbeb; }' newline ...
'.safety-red    { border-left: 4px solid var(--red);   background: #fef2f2; }' newline ...
'.safety-gray   { border-left: 4px solid var(--gray);  background: #f9fafb; }' newline ...
'.safety-info   { border-left: 4px solid var(--info);  background: #eff6ff; }' newline ...
'.safety-label  { font-size: 0.8em; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }' newline ...
'.safety-value  { font-size: 1.5em; font-weight: 700; margin: 4px 0; }' newline ...
'.risk-limit  { font-size: 0.75em; color: #94a3b8; }' newline ...
'.safety-footnote { font-size: 0.8em; color: #94a3b8; margin-top: 8px; }' newline ...
newline ...
'/* Range table row colors */' newline ...
'.row-green { background: #f0fdf4; }' newline ...
'.row-amber { background: #fffbeb; }' newline ...
'.row-red   { background: #fef2f2; font-weight: 600; }' newline ...
'.row-gray  { background: #f9fafb; color: #94a3b8; }' newline ...
'.row-info  {}' newline ...
newline ...
'/* Tables */' newline ...
'.info-table th { text-align: left; padding: 4px 16px 4px 0; color: #64748b; font-weight: 500; }' newline ...
'.info-table td { padding: 4px 0; }' newline ...
'.table-wrapper { overflow-x: auto; margin: 12px 0; }' newline ...
'.data-table { width: 100%; border-collapse: collapse; font-size: 0.9em; }' newline ...
'.data-table thead { background: #f1f5f9; }' newline ...
'.data-table th, .data-table td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e2e8f0; white-space: nowrap; }' newline ...
newline ...
'/* Images */' newline ...
'.image-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(400px, 100%), 1fr)); gap: 16px; margin: 16px 0; }' newline ...
'.image-grid--3col { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 16px 0; }' newline ...
'@media (max-width: 700px) { .image-grid--3col { grid-template-columns: 1fr; } }' newline ...
'figure { margin: 0; min-width: 0; overflow: hidden; }' newline ...
'figure img { display: block; width: 100%; height: auto; border-radius: 4px; border: 1px solid #e2e8f0; cursor: zoom-in; }' newline ...
'figcaption { font-size: 0.85em; color: #64748b; margin-top: 4px; text-align: center; }' newline ...
'.placeholder-img { display:flex; flex-direction:column; align-items:center; justify-content:center; ' ...
  'min-height:120px; background:#f1f5f9; border:1px dashed #cbd5e1; border-radius:4px; color:#94a3b8; font-size:0.85em; padding:12px; text-align:center; }' newline ...
newline ...
'/* Banners */' newline ...
'.medium-banner { padding: 12px 16px; border-radius: 6px; margin-bottom: 16px; font-size: 0.9em; }' newline ...
'.medium-water   { background: #eff6ff; border-left: 4px solid var(--info);  color: #1e40af; }' newline ...
'.medium-layered { background: #fffbeb; border-left: 4px solid var(--amber); color: #92400e; }' newline ...
newline ...
'/* Nav */' newline ...
'.toc { position: sticky; top: 0; z-index: 100; background: white; border-radius: 8px; ' ...
  'padding: 10px 20px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); ' ...
  'display: flex; align-items: center; gap: 12px; flex-wrap: wrap; }' newline ...
'.toc a { text-decoration: none; color: #475569; font-size: 0.85em; padding: 4px 10px; ' ...
  'border-radius: 4px; white-space: nowrap; }' newline ...
'.toc a:hover { background: #f1f5f9; }' newline ...
newline ...
'/* Collapsible sections */' newline ...
'details.report-section { padding: 0; }' newline ...
'details.report-section > summary { cursor: pointer; list-style: none; padding: 16px 24px; display: flex; align-items: center; gap: 8px; }' newline ...
'details.report-section > summary::-webkit-details-marker { display: none; }' newline ...
'details.report-section > summary::before { content: "\25B6"; font-size: 0.7em; transition: transform 0.2s ease; flex-shrink: 0; }' newline ...
'details[open].report-section > summary::before { transform: rotate(90deg); }' newline ...
'details.report-section > summary > h2 { border-bottom: none; margin-bottom: 0; padding-bottom: 0; }' newline ...
'details.report-section > .section-content { padding: 0 24px 24px 24px; }' newline ...
newline ...
'/* Lightbox */' newline ...
'.lb-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.85); z-index: 1000; ' ...
  'display: flex; align-items: center; justify-content: center; cursor: zoom-out; }' newline ...
'.lb-overlay img { max-width: 90vw; max-height: 85vh; object-fit: contain; border-radius: 4px; }' newline ...
'.lb-close { position: fixed; top: 16px; right: 24px; color: white; font-size: 2em; cursor: pointer; z-index: 1001; line-height: 1; }' newline ...
newline ...
'/* Misc */' newline ...
'.placeholder { color: #94a3b8; font-style: italic; }' newline ...
'.note { font-size: 0.85em; color: #64748b; margin: 8px 0; }' newline ...
'code { background: #f1f5f9; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }' newline ...
'footer { text-align: center; color: #94a3b8; font-size: 0.8em; padding: 20px 0; }' newline ...
'@media print { body { background: white; } .report-section { box-shadow: none; border: 1px solid #e2e8f0; } ' ...
  'details { display: block; } details > summary { display: none; } details > .section-content { padding: 0 24px 24px; } ' ...
  '.toc { display: none; } .lb-overlay { display: none; } }' newline ...
];
end
