function report_path = generate_multi_isppa_report(parameters, multi_isppa)
% GENERATE_MULTI_ISPPA_REPORT  Generate an HTML report comparing multiple ISPPA levels
%
% Loads acoustic/thermal CSV tables for each ISPPA variant and writes a
% self-contained HTML report showing how key metrics scale with ISPPA.
%
% Use as:
%   report_path = generate_multi_isppa_report(parameters, multi_isppa)
%
% Input:
%   parameters  - simulation parameters struct
%   multi_isppa - struct with fields:
%                   targets_wcm2 : vector of ISPPA values (W/cm²)
%                   affixes      : cell array of output affixes (one per target)
%
% Output:
%   report_path - path to the generated HTML file

arguments
    parameters  (1,1) struct
    multi_isppa (1,1) struct
end

report_path = '';

try
    subject_id = parameters.subject_id;
    medium     = parameters.simulation.medium;
    output_dir = parameters.io.output_dir;
    base_affix = '';
    if isfield(parameters, 'io') && isfield(parameters.io, 'output_affix')
        base_affix = parameters.io.output_affix;
    end

    targets = multi_isppa.targets_wcm2(:)';
    affixes = multi_isppa.affixes(:)';
    n       = numel(targets);

    is_layered = contains(medium, {'layered', 'phantom'});

    %% Load CSV tables for each target
    tables = cell(1, n);
    for ti = 1:n
        csv_path = fullfile(output_dir, ...
            sprintf('sub-%03d_%s_output_table%s.csv', subject_id, medium, affixes{ti}));
        if isfile(csv_path)
            try
                tables{ti} = readtable(csv_path, 'VariableNamingRule', 'preserve');
            catch
                tables{ti} = [];
            end
        end
    end

    if all(cellfun(@isempty, tables))
        warning('generate_multi_isppa_report:noData', ...
            'No output tables found in %s — report will be empty.', output_dir);
    end

    %% Build HTML
    html_parts = {};
    html_parts{end+1} = '<!DOCTYPE html>';
    html_parts{end+1} = '<html lang="en">';
    html_parts{end+1} = '<head>';
    html_parts{end+1} = '<meta charset="UTF-8">';
    html_parts{end+1} = '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
    html_parts{end+1} = sprintf('<title>PRESTUS Multi-ISPPA Report — sub-%03d %s</title>', subject_id, medium);
    html_parts{end+1} = '<style>';
    html_parts{end+1} = css_styles_base();
    html_parts{end+1} = '</style>';
    html_parts{end+1} = '</head>';
    html_parts{end+1} = '<body>';

    html_parts{end+1} = build_toc(is_layered);
    html_parts{end+1} = build_header(subject_id, medium, output_dir, targets, affixes);

    try
        html_parts{end+1} = html_utils.collapsible('Acoustic Results', ...
            build_acoustic_section(tables, targets, affixes, parameters, subject_id, medium, is_layered), ...
            true, 'acoustic');
    catch ME
        html_parts{end+1} = html_utils.section_error('Acoustic Results', ME);
    end

    if is_layered
        try
            html_parts{end+1} = html_utils.collapsible('Thermal Results', ...
                build_thermal_section(tables, targets, affixes, parameters, subject_id, medium), ...
                true, 'thermal');
        catch ME
            html_parts{end+1} = html_utils.section_error('Thermal Results', ME);
        end
    end

    try
        html_parts{end+1} = html_utils.collapsible('Raw Data Tables', ...
            build_tables_section(tables, targets), ...
            false, 'tables');
    catch ME
        html_parts{end+1} = html_utils.section_error('Raw Data Tables', ME);
    end

    html_parts{end+1} = '<footer>';
    html_parts{end+1} = sprintf('<p>Generated by PRESTUS multi-ISPPA report — %s</p>', ...
        datestr(now, 'yyyy-mm-dd HH:MM:SS'));
    html_parts{end+1} = '</footer>';
    html_parts{end+1} = html_utils.lightbox();
    html_parts{end+1} = '</body>';
    html_parts{end+1} = '</html>';

    %% Write file
    report_filename = sprintf('sub-%03d_%s_multi_isppa_report%s.html', subject_id, medium, base_affix);
    report_path = fullfile(output_dir, report_filename);
    fid = fopen(report_path, 'w', 'n', 'UTF-8');
    if fid == -1
        warning('generate_multi_isppa_report:fileOpen', 'Cannot open %s for writing.', report_path);
        return
    end
    fprintf(fid, '%s\n', html_parts{:});
    fclose(fid);
    fprintf('Multi-ISPPA report saved to: %s\n', report_path);

catch ME
    warning('generate_multi_isppa_report:failed', ...
        'Report generation failed: %s\n%s', ME.message, getReport(ME, 'extended'));
    report_path = '';
end

end

%% ========================================================================
%  SECTION BUILDERS
%% ========================================================================

function html = build_toc(is_layered)
    html = '<nav class="toc" id="toc">';
    html = [html '<strong style="font-size:0.85em;color:#475569;">Multi-ISPPA</strong>'];
    html = [html '<a href="#header">Header</a>'];
    html = [html '<a href="#acoustic">Acoustic</a>'];
    if is_layered
        html = [html '<a href="#thermal">Thermal</a>'];
    end
    html = [html '<a href="#tables">Tables</a>'];
    html = [html '</nav>'];
end

function html = build_header(subject_id, medium, output_dir, targets, affixes)
    html = '<section class="report-section" id="header">';
    html = [html '<h1>PRESTUS Multi-ISPPA Report</h1>'];
    html = [html '<table class="info-table">'];
    html = [html sprintf('<tr><th>Subject</th><td>sub-%03d</td></tr>', subject_id)];
    html = [html sprintf('<tr><th>Medium</th><td>%s</td></tr>', html_utils.escape(medium))];
    html = [html sprintf('<tr><th>ISPPA targets (W/cm²)</th><td>%s</td></tr>', ...
        strjoin(arrayfun(@(x) sprintf('%.0f', x), targets, 'UniformOutput', false), ', '))];
    html = [html sprintf('<tr><th>Output dir</th><td>%s</td></tr>', html_utils.escape(output_dir))];
    html = [html sprintf('<tr><th>Generated</th><td>%s</td></tr>', datestr(now, 'yyyy-mm-dd HH:MM:SS'))];
    html = [html '</table>'];
    html = [html '</section>'];
end

function html = build_safety_dashboard(tables, targets, is_layered)
    n = numel(targets);
    limits = struct();
    if is_layered
        limits = get_risk_limits(true);
    end
    metric_names = fieldnames(limits);

    html = '<section class="report-section" id="safety">';
    html = [html '<h2>Safety Dashboard</h2>'];

    if ~is_layered
        html = [html '<div class="medium-banner medium-water">' ...
            '<strong>Water / Free-field</strong> &mdash; tissue-specific non-significant risk limits not applicable.</div>'];
    end

    html = [html '<div class="safety-grid">'];

    for i = 1:length(metric_names)
        name = metric_names{i};
        info = limits.(name);

        vals = NaN(1, n);
        for ti = 1:n
            if ~isempty(tables{ti}) && ismember(name, tables{ti}.Properties.VariableNames)
                col = tables{ti}.(name);
                if isnumeric(col) && ~isempty(col)
                    vals(ti) = col(end);
                end
            end
        end

        max_val = max(vals(~isnan(vals)));
        if isempty(max_val); max_val = NaN; end
        color = risk_color(max_val, info.limit);

        html = [html sprintf('<div class="safety-card safety-%s">', color)];
        html = [html sprintf('<div class="safety-label">%s</div>', html_utils.escape(info.label))];

        if all(isnan(vals))
            html = [html '<div class="safety-value">N/A</div>'];
            html = [html '<div class="risk-limit">No data</div>'];
        else
            html = [html sprintf('<div class="safety-value">%.3g</div>', max_val)];
            if ~isinf(info.limit)
                html = [html sprintf('<div class="risk-limit">NSR limit: %.3g %s</div>', info.limit, info.unit)];
            else
                html = [html sprintf('<div class="risk-limit">%s (informational)</div>', info.unit)];
            end

            % Show trend across targets
            trend = '<div style="font-size:0.75em;color:#64748b;margin-top:4px;">';
            for ti = 1:n
                if ~isnan(vals(ti))
                    trend = [trend sprintf('<span style="margin-right:6px;">%.0f&thinsp;W/cm²: %.3g</span>', targets(ti), vals(ti))];
                end
            end
            trend = [trend '</div>'];
            html = [html trend];
        end

        html = [html '</div>'];
    end

    html = [html '</div>'];
    html = [html '<p class="safety-footnote">Non-significant risk limits: ITRUSST consensus (Aubry et al., 2025). ' ...
        'Card colour reflects the highest ISPPA value.</p>'];
    html = [html '</section>'];
end

function html = build_acoustic_section(tables, targets, affixes, parameters, subject_id, medium, is_layered)
    if is_layered
        key_metrics = {'Isppa', 'Isppa_brain', 'Isppa_skull', 'Isppa_skin', ...
                       'real_focal_distance_mm', 'MI_brain', 'MI_skull', 'MI_skin', 'MI_tc', ...
                       'Ipa_target', 'halfmax_ISPPA_volume_brain_mm3'};
    else
        key_metrics = {'Isppa', 'Isppa_after_exitplane', 'Psptp', 'Ptp_target', ...
                       'real_focal_distance_mm', 'Ipa_target'};
    end

    html = '<h3>Key Acoustic Metrics</h3>';
    html = [html build_metric_table(tables, targets, key_metrics, is_layered)];

    html = [html '<h3 style="margin-top:24px;">Intensity Maps</h3>'];
    html = [html '<div class="image-grid image-grid--3col">'];
    any_found = false;
    for ti = 1:numel(targets)
        lbl = sprintf('%.0f W/cm²', targets(ti));
        img_path = fullfile(parameters.io.output_dir, ...
            sprintf('sub-%03d_%s_intensity_y%s.png', subject_id, medium, affixes{ti}));
        img_html = html_utils.embed_image(img_path, lbl, lbl);
        if ~isempty(img_html)
            html = [html img_html];
            any_found = true;
        else
            html = [html sprintf('<figure><div class="placeholder-img">%s<br>Image not found</div></figure>', html_utils.escape(lbl))];
        end
    end
    if ~any_found
        html = regexprep(html, '<h3[^>]*>Intensity Maps</h3>', '');
    end
    html = [html '</div>'];
end

function html = build_thermal_section(tables, targets, affixes, parameters, subject_id, medium)
    key_metrics = {'maxT', 'maxT_brain', 'maxT_skull', 'maxT_skin', ...
                   'riseT_brain', 'riseT_skull', 'riseT_skin', ...
                   'CEM43_brain', 'CEM43_skull', 'CEM43_skin'};

    html = '<h3>Thermal Metrics</h3>';
    html = [html build_metric_table(tables, targets, key_metrics, true)];

    html = [html '<h3 style="margin-top:24px;">Temperature Maps</h3>'];
    html = [html '<div class="image-grid image-grid--3col">'];
    any_found = false;
    for ti = 1:numel(targets)
        lbl = sprintf('%.0f W/cm²', targets(ti));
        img_path = fullfile(parameters.io.output_dir, ...
            sprintf('sub-%03d_%s_thermal_max%s.png', subject_id, medium, affixes{ti}));
        img_html = html_utils.embed_image(img_path, lbl, lbl);
        if ~isempty(img_html)
            html = [html img_html];
            any_found = true;
        else
            html = [html sprintf('<figure><div class="placeholder-img">%s<br>Image not found</div></figure>', html_utils.escape(lbl))];
        end
    end
    if ~any_found
        html = regexprep(html, '<h3[^>]*>Temperature Maps</h3>', '');
    end
    html = [html '</div>'];
end

function html = build_tables_section(tables, targets)
    html = '';
    for ti = 1:numel(targets)
        lbl = sprintf('%.0f W/cm²', targets(ti));
        if isempty(tables{ti})
            html = [html sprintf('<h3>%s</h3><p class="placeholder">Table not found.</p>', html_utils.escape(lbl))];
            continue;
        end
        html = [html sprintf('<h3>%s</h3>', html_utils.escape(lbl))];
        html = [html table2html(tables{ti})];
    end
end

%% ========================================================================
%  METRIC TABLE
%% ========================================================================

function html = build_metric_table(tables, targets, metric_names, use_limits)
    n = numel(targets);
    limits = struct();
    if use_limits
        limits = get_risk_limits(true);
    end

    html = '<div class="table-wrapper"><table class="data-table"><thead><tr>';
    html = [html '<th>Metric</th>'];
    for ti = 1:n
        html = [html sprintf('<th>%.0f W/cm²</th>', targets(ti))];
    end
    html = [html '<th>Limit</th></tr></thead><tbody>'];

    for m = 1:numel(metric_names)
        name = metric_names{m};

        vals = NaN(1, n);
        for ti = 1:n
            if ~isempty(tables{ti}) && ismember(name, tables{ti}.Properties.VariableNames)
                col = tables{ti}.(name);
                if isnumeric(col) && ~isempty(col)
                    vals(ti) = col(end);
                end
            end
        end

        limit_str = '—';
        limit_val = Inf;
        if isfield(limits, name)
            limit_val = limits.(name).limit;
            if ~isinf(limit_val)
                limit_str = sprintf('%.3g %s', limit_val, limits.(name).unit);
            end
        end

        worst = max(vals(~isnan(vals)));
        if isempty(worst); worst = NaN; end
        row_color = risk_color(worst, limit_val);

        html = [html sprintf('<tr class="row-%s">', row_color)];
        html = [html sprintf('<td><strong>%s</strong></td>', html_utils.escape(name))];
        for ti = 1:n
            if isnan(vals(ti))
                html = [html '<td>N/A</td>'];
            else
                html = [html sprintf('<td>%.4g</td>', vals(ti))];
            end
        end
        html = [html sprintf('<td>%s</td>', html_utils.escape(limit_str))];
        html = [html '</tr>'];
    end

    html = [html '</tbody></table></div>'];
end
