classdef report_scripts
% REPORT_SCRIPTS  Shared inline JavaScript for PRESTUS HTML reports.
%
% All methods are static and return a self-contained <script> string (no
% external dependencies, so reports stay offline-portable). The MATLAB side
% still produces any data payloads (via jsonencode); only the behaviour lives
% here, shared by the per-subject and group reports.
%
% Methods:
%   report_scripts.common()         theme toggle, in-page search, scroll-spy,
%                                    meter-fill animation, lightbox (zoom +
%                                    side-by-side compare)
%   report_scripts.group_runtime()  sortable roster + client-side analysis
%                                    charts (reads PRESTUS_SUBJECTS / _METRICS)
%
% See also: GENERATE_SIMULATION_REPORT, GENERATE_GROUP_REPORT, CSS_STYLES_BASE

    methods (Static)

        function html = common()
        % Theme, search, scroll-spy, meter fill, and the lightbox behaviour.
            js = [ ...
'(function(){var root=document.documentElement;' ...
'function setTheme(t){root.setAttribute("data-theme",t);' ...
'var s=document.getElementById("theme-sun"),m=document.getElementById("theme-moon");' ...
'if(s)s.style.display=t==="dark"?"none":"block";if(m)m.style.display=t==="dark"?"block":"none";' ...
'try{localStorage.setItem("prestus-theme",t);}catch(e){}}' ...
'var stored=null;try{stored=localStorage.getItem("prestus-theme");}catch(e){}' ...
'setTheme(stored||(window.matchMedia&&matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light"));' ...
'var tb=document.getElementById("theme-btn");if(tb)tb.addEventListener("click",function(){setTheme(root.getAttribute("data-theme")==="dark"?"light":"dark");});' ...
... % meter fill (setTimeout fires even when the tab is backgrounded)
'setTimeout(function(){[].forEach.call(document.querySelectorAll(".safety-bar[data-pct]"),function(b){var p=Math.min(100,Math.max(2,parseFloat(b.getAttribute("data-pct"))))+"%";b.style.width="0%";void b.offsetWidth;b.style.width=p;});},60);' ...
... % scroll-spy
'var links=[].slice.call(document.querySelectorAll(".toc a[href^=\"#\"]"));' ...
'var secs=links.map(function(a){return document.querySelector(a.getAttribute("href"));}).filter(Boolean);' ...
'if(window.IntersectionObserver){var sp=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){links.forEach(function(l){l.classList.toggle("active",l.getAttribute("href")==="#"+e.target.id);});}});},{rootMargin:"-45% 0px -50% 0px"});secs.forEach(function(s){sp.observe(s);});}' ...
... % in-page search highlight
'var si=document.getElementById("report-search");' ...
'function unmark(scope){[].forEach.call(scope.querySelectorAll("mark.s"),function(m){var t=document.createTextNode(m.textContent);m.parentNode.replaceChild(t,m);});}' ...
'function walk(node,rx){if(node.nodeType===3){if(rx.test(node.nodeValue)){var span=document.createElement("span");span.innerHTML=node.nodeValue.replace(rx,"<mark class=\"s\">$1</mark>");node.parentNode.replaceChild(span,node);return span;}return null;}' ...
'if(node.nodeType===1&&!/SCRIPT|STYLE|MARK|INPUT|TEXTAREA/.test(node.tagName)){var first=null;[].slice.call(node.childNodes).forEach(function(c){var r=walk(c,rx);if(r&&!first)first=r;});return first;}return null;}' ...
'function runSearch(q){var scopes=document.querySelectorAll(".report-section");[].forEach.call(scopes,unmark);' ...
'if(!q||q.length<2)return;var rx=new RegExp("("+q.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+")","gi");var first=null;' ...
'[].forEach.call(document.querySelectorAll(".report-section"),function(c){var opened=false;if(c.tagName==="DETAILS"&&!c.open){c.open=true;opened=true;}var f=walk(c,rx);if(f&&!first)first=f;if(opened&&!c.querySelector("mark.s"))c.open=false;});' ...
'if(first)first.scrollIntoView({behavior:"smooth",block:"center"});}' ...
'if(si){var dt;si.addEventListener("input",function(e){clearTimeout(dt);var v=e.target.value.trim();dt=setTimeout(function(){runSearch(v);},200);});}' ...
'document.addEventListener("keydown",function(e){if(e.key==="/"&&si&&document.activeElement!==si&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName)){e.preventDefault();si.focus();}});' ...
... % lightbox + zoom + compare
'var lb=document.getElementById("lightbox");if(lb){var stage=document.getElementById("lb-stage"),cmp=[],zoom=1;' ...
'function apply(){[].forEach.call(stage.querySelectorAll("img"),function(i){i.style.transform="scale("+zoom+")";});}' ...
'function show(items){stage.innerHTML="";zoom=1;items.forEach(function(it){var fg=document.createElement("figure");var im=document.createElement("img");im.src=it.src;fg.appendChild(im);if(it.cap){var fc=document.createElement("figcaption");fc.textContent=it.cap;fg.appendChild(fc);}stage.appendChild(fg);});lb.style.display="flex";apply();}' ...
'function close(){lb.style.display="none";}' ...
'var zb=document.getElementById("lb-zoom");if(zb)zb.addEventListener("click",function(){zoom=Math.min(3,zoom+0.4);apply();});' ...
'var rb=document.getElementById("lb-reset");if(rb)rb.addEventListener("click",function(){zoom=1;apply();});' ...
'var cb=lb.querySelector(".lb-close");if(cb)cb.addEventListener("click",close);' ...
'lb.addEventListener("click",function(e){if(e.target===lb)close();});' ...
'document.addEventListener("keydown",function(e){if(e.key==="Escape")close();});' ...
'[].forEach.call(document.querySelectorAll(".image-grid figure,.image-grid--3col figure,.image-grid--wide figure,.image-grid--narrow figure"),function(fig){' ...
'var img=fig.querySelector("img");if(!img)return;var cap=fig.querySelector("figcaption");var capText=cap?cap.textContent:"";' ...
'var btn=document.createElement("span");btn.className="cmp";btn.textContent="compare";' ...
'if(cap)cap.appendChild(btn);else fig.appendChild(btn);' ...
'btn.addEventListener("click",function(e){e.stopPropagation();var i=cmp.indexOf(fig);if(i>-1){cmp.splice(i,1);btn.classList.remove("on");}else{if(cmp.length>=2){var old=cmp.shift();var ob=old.querySelector(".cmp");if(ob)ob.classList.remove("on");}cmp.push(fig);btn.classList.add("on");}});' ...
'img.addEventListener("click",function(){var self={src:img.src,cap:capText};if(cmp.length===1&&cmp[0]!==fig){var o=cmp[0].querySelector("img");var oc=cmp[0].querySelector("figcaption");show([{src:o.src,cap:oc?oc.textContent:""},self]);}else{show([self]);}});});}' ...
'})();' ];
            html = ['<script>' js '</script>'];
        end

        function html = group_runtime()
        % Sortable roster + analysis charts. Expects two globals already
        % emitted by the report: PRESTUS_SUBJECTS (array of {id, <metric>:val})
        % and PRESTUS_METRICS (array of {k,label,unit,limit,dom}).
            js = [ ...
'(function(){if(!window.PRESTUS_SUBJECTS||!window.PRESTUS_METRICS)return;' ...
'var SUB=window.PRESTUS_SUBJECTS,MET=window.PRESTUS_METRICS;' ...
'var byK={};MET.forEach(function(m){byK[m.k]=m;});' ...
'function isLim(m){return m&&isFinite(m.limit);}' ...
'function cls(v,lim){if(!isFinite(lim))return"info";if(v>lim)return"red";if(v>=0.5*lim)return"amber";return"green";}' ...
... % --- sortable roster (sorts existing server-rendered rows) ---
'var tbl=document.getElementById("roster-table");' ...
'if(tbl){var tb=tbl.tBodies[0];var sortKey=null,dir=1;' ...
'[].forEach.call(tbl.tHead.rows[0].cells,function(th){if(!th.hasAttribute("data-col"))return;th.classList.add("sortable");' ...
'var ar=document.createElement("span");ar.className="ar";ar.textContent=" ⇅";th.appendChild(ar);' ...
'th.addEventListener("click",function(){var k=th.getAttribute("data-col");if(sortKey===k)dir=-dir;else{sortKey=k;dir=1;}' ...
'[].forEach.call(tbl.tHead.rows[0].cells,function(c){c.classList.remove("sort");var a=c.querySelector(".ar");if(a)a.textContent=" ⇅";});' ...
'th.classList.add("sort");ar.textContent=dir>0?" ▲":" ▼";' ...
'var rows=[].slice.call(tb.rows);rows.sort(function(a,b){var x=a.querySelector("[data-col=\""+k+"\"]"),y=b.querySelector("[data-col=\""+k+"\"]");' ...
'var xv=x?parseFloat(x.getAttribute("data-value")):NaN,yv=y?parseFloat(y.getAttribute("data-value")):NaN;' ...
'if(isNaN(xv))return 1;if(isNaN(yv))return -1;return (xv-yv)*dir;});rows.forEach(function(r){tb.appendChild(r);});});});}' ...
... % --- analysis charts ---
'var plot=document.getElementById("an-plot");if(!plot)return;var legend=document.getElementById("an-legend");var view="dist";' ...
'var SVGNS="http://www.w3.org/2000/svg";' ...
'function E(n,a){var e=document.createElementNS(SVGNS,n);for(var k in a)e.setAttribute(k,a[k]);return e;}' ...
'function T(x,y,s,a){var t=E("text",Object.assign({x:x,y:y},a||{}));t.textContent=s;return t;}' ...
'function clearP(){plot.innerHTML="";if(legend)legend.innerHTML="";}' ...
'function ax(x0,y0,x1,y1){plot.appendChild(E("line",{x1:x0,y1:y0,x2:x0,y2:y1,stroke:"var(--ink-4)","stroke-width":1}));plot.appendChild(E("line",{x1:x0,y1:y0,x2:x1,y2:y0,stroke:"var(--ink-4)","stroke-width":1}));}' ...
'function vals(k){return SUB.map(function(s){return s[k];}).filter(function(v){return typeof v==="number"&&!isNaN(v);});}' ...
'function selVal(id){var e=document.getElementById(id);return e?e.value:null;}' ...
... % distribution / histogram
'function drawDist(){clearP();var m=byK[selVal("an-dist")];if(!m)return;var data=vals(m.k);if(!data.length)return;' ...
'var W=760,H=320,L=46,R=20,Tt=24,B=44,x0=L,x1=W-R,y0=H-B,y1=Tt;' ...
'var lo=Math.min.apply(null,data),hi=Math.max.apply(null,data);if(isFinite(m.limit))hi=Math.max(hi,m.limit);var pad=(hi-lo||1)*0.15;lo=Math.max(0,lo-pad);hi=hi+pad;' ...
'var nb=6,bw=(hi-lo)/nb,bins=[];for(var i=0;i<nb;i++)bins.push(0);data.forEach(function(v){var bi=Math.min(nb-1,Math.floor((v-lo)/bw));bins[bi]++;});' ...
'var maxC=Math.max.apply(null,bins.concat([1]));var X=function(v){return x0+(v-lo)/(hi-lo)*(x1-x0);};var Y=function(c){return y0-c/maxC*(y0-y1);};ax(x0,y0,x1,y1);' ...
'for(var c=1;c<=maxC;c++){plot.appendChild(E("line",{x1:x0,y1:Y(c),x2:x1,y2:Y(c),stroke:"var(--line)","stroke-width":1}));plot.appendChild(T(x0-8,Y(c)+4,c,{fill:"var(--ink-4)","font-size":11,"text-anchor":"end"}));}' ...
'bins.forEach(function(c,i){var bx=X(lo+i*bw),bx2=X(lo+(i+1)*bw),col=cls(lo+(i+0.5)*bw,m.limit);plot.appendChild(E("rect",{x:bx+2,y:Y(c),width:Math.max(1,bx2-bx-4),height:y0-Y(c),rx:3,fill:"var(--"+col+")","fill-opacity":0.85}));});' ...
'for(var t=0;t<=4;t++){var vv=lo+(hi-lo)*t/4;plot.appendChild(T(X(vv),y0+18,vv.toFixed(1),{fill:"var(--ink-4)","font-size":11,"text-anchor":"middle"}));}' ...
'if(isFinite(m.limit)){plot.appendChild(E("line",{x1:X(m.limit),y1:y1,x2:X(m.limit),y2:y0,stroke:"var(--red)","stroke-width":2,"stroke-dasharray":"5 4"}));plot.appendChild(T(X(m.limit),y1-6,"NSR "+m.limit,{fill:"var(--red)","font-size":11,"text-anchor":"middle"}));}' ...
'var mean=data.reduce(function(a,b){return a+b;},0)/data.length;plot.appendChild(E("line",{x1:X(mean),y1:y1,x2:X(mean),y2:y0,stroke:"var(--ink)","stroke-width":1.5}));' ...
'if(legend)legend.innerHTML="<span><i style=\"background:var(--green)\"></i>&lt;50%</span><span><i style=\"background:var(--amber)\"></i>50-100%</span><span><i style=\"background:var(--red)\"></i>over</span> &middot; "+data.length+" subjects &middot; "+m.label+(m.unit?" ("+m.unit+")":"")+", count on Y";}' ...
... % correlation / scatter
'function drawCorr(){clearP();var mx=byK[selVal("an-x")],my=byK[selVal("an-y")];if(!mx||!my)return;' ...
'var W=760,H=320,L=52,R=20,Tt=24,B=44,x0=L,x1=W-R,y0=H-B,y1=Tt;var xs=vals(mx.k),ys=vals(my.k);if(!xs.length)return;' ...
'var xlo=Math.min.apply(null,xs),xhi=Math.max.apply(null,xs),ylo=Math.min.apply(null,ys),yhi=Math.max.apply(null,ys);if(isFinite(my.limit))yhi=Math.max(yhi,my.limit);' ...
'var xp=(xhi-xlo||1)*0.12,yp=(yhi-ylo||1)*0.12;xlo-=xp;xhi+=xp;ylo=Math.max(0,ylo-yp);yhi+=yp;' ...
'var X=function(v){return x0+(v-xlo)/(xhi-xlo)*(x1-x0);},Y=function(v){return y0-(v-ylo)/(yhi-ylo)*(y0-y1);};ax(x0,y0,x1,y1);' ...
'for(var t=0;t<=4;t++){var xv=xlo+(xhi-xlo)*t/4,yv=ylo+(yhi-ylo)*t/4;plot.appendChild(T(X(xv),y0+18,xv.toFixed(1),{fill:"var(--ink-4)","font-size":11,"text-anchor":"middle"}));plot.appendChild(T(x0-8,Y(yv)+4,yv.toFixed(1),{fill:"var(--ink-4)","font-size":11,"text-anchor":"end"}));}' ...
'if(isFinite(my.limit)){plot.appendChild(E("line",{x1:x0,y1:Y(my.limit),x2:x1,y2:Y(my.limit),stroke:"var(--red)","stroke-width":2,"stroke-dasharray":"5 4"}));plot.appendChild(T(x1,Y(my.limit)-6,"NSR "+my.limit,{fill:"var(--red)","font-size":11,"text-anchor":"end"}));}' ...
'SUB.forEach(function(s){if(typeof s[mx.k]!=="number"||typeof s[my.k]!=="number")return;var col=cls(s[my.k],my.limit);plot.appendChild(E("circle",{cx:X(s[mx.k]),cy:Y(s[my.k]),r:6,fill:"var(--"+col+")","fill-opacity":0.85,stroke:"var(--surface)","stroke-width":1.5}));plot.appendChild(T(X(s[mx.k]),Y(s[my.k])-10,s.id,{fill:"var(--ink-4)","font-size":9,"text-anchor":"middle"}));});' ...
'plot.appendChild(T((x0+x1)/2,H-6,mx.label+(mx.unit?" ("+mx.unit+")":""),{fill:"var(--ink-3)","font-size":12,"text-anchor":"middle"}));' ...
'if(legend)legend.innerHTML="Each point = one subject &middot; colour by Y vs its NSR limit &middot; X = "+mx.label;}' ...
... % by condition
'function drawCond(){clearP();var m=byK[selVal("an-cond")],by=selVal("an-by")||"id";if(!m)return;var groups={};' ...
'SUB.forEach(function(s){var g=s[by];if(g===undefined)g="all";(groups[g]=groups[g]||[]).push(s[m.k]);});' ...
'var keys=Object.keys(groups).sort(function(a,b){return (parseFloat(a)||a)-(parseFloat(b)||b);});' ...
'var W=760,H=320,L=52,R=20,Tt=24,B=50,x0=L,x1=W-R,y0=H-B,y1=Tt;var all=vals(m.k);if(!all.length)return;var hi=Math.max.apply(null,all);if(isFinite(m.limit))hi=Math.max(hi,m.limit);hi*=1.12;var lo=0;' ...
'var Y=function(v){return y0-(v-lo)/(hi-lo)*(y0-y1);};ax(x0,y0,x1,y1);' ...
'if(isFinite(m.limit)){plot.appendChild(E("line",{x1:x0,y1:Y(m.limit),x2:x1,y2:Y(m.limit),stroke:"var(--red)","stroke-width":2,"stroke-dasharray":"5 4"}));plot.appendChild(T(x1,Y(m.limit)-6,"NSR "+m.limit,{fill:"var(--red)","font-size":11,"text-anchor":"end"}));}' ...
'for(var t=0;t<=4;t++){var vv=lo+(hi-lo)*t/4;plot.appendChild(T(x0-8,Y(vv)+4,vv.toFixed(1),{fill:"var(--ink-4)","font-size":11,"text-anchor":"end"}));}' ...
'var bw=(x1-x0)/keys.length;keys.forEach(function(k,i){var vs=groups[k].filter(function(v){return typeof v==="number";});if(!vs.length)return;var mn=Math.min.apply(null,vs),mx2=Math.max.apply(null,vs),mean=vs.reduce(function(a,b){return a+b;},0)/vs.length;var cx=x0+bw*(i+0.5),col=cls(mx2,m.limit);' ...
'plot.appendChild(E("line",{x1:cx,y1:Y(mn),x2:cx,y2:Y(mx2),stroke:"var(--"+col+")","stroke-width":3,"stroke-linecap":"round","stroke-opacity":0.5}));' ...
'vs.forEach(function(v){plot.appendChild(E("circle",{cx:cx,cy:Y(v),r:4,fill:"var(--"+col+")","fill-opacity":0.55}));});' ...
'plot.appendChild(E("rect",{x:cx-22,y:Y(mean)-1.5,width:44,height:3,rx:1.5,fill:"var(--ink)"}));' ...
'plot.appendChild(T(cx,Y(mean)-8,mean.toFixed(1),{fill:"var(--ink)","font-size":11,"text-anchor":"middle","font-weight":600}));' ...
'plot.appendChild(T(cx,y0+18,by+" "+k,{fill:"var(--ink-3)","font-size":11,"text-anchor":"middle"}));' ...
'plot.appendChild(T(cx,y0+34,"n="+vs.length,{fill:"var(--ink-4)","font-size":10,"text-anchor":"middle"}));});' ...
'if(legend)legend.innerHTML="Bar = group mean &middot; whisker = min-max &middot; dots = subjects &middot; "+m.label;}' ...
'function render(){if(view==="dist")drawDist();else if(view==="corr")drawCorr();else drawCond();}' ...
'[].forEach.call(document.querySelectorAll(".an-tab"),function(t){t.addEventListener("click",function(){[].forEach.call(document.querySelectorAll(".an-tab"),function(x){x.classList.remove("on");});t.classList.add("on");view=t.getAttribute("data-view");' ...
'document.getElementById("an-c-dist").style.display=view==="dist"?"flex":"none";document.getElementById("an-c-corr").style.display=view==="corr"?"flex":"none";document.getElementById("an-c-cond").style.display=view==="cond"?"flex":"none";render();});});' ...
'["an-dist","an-x","an-y","an-cond","an-by"].forEach(function(id){var e=document.getElementById(id);if(e)e.addEventListener("change",render);});' ...
'render();' ...
'})();' ];
            html = ['<script>' js '</script>'];
        end

    end
end
