function [sensor_data, parameters, trans_pos, focus_pos, segmentation, medium_masks, kwave_medium, kgrid, source, source_labels] = ...
            acoustic_convert_axisymmetry(parameters, sensor_data, trans_pos, focus_pos, ...
            segmentation, medium_masks, kwave_medium, source, source_labels)

    % if using axisymmetric settings and requesting heating simulations, reshape output to 3D
    if isfield(parameters, 'run_heating_sims') && parameters.run_heating_sims==1
        % when follow-up thermal simulation is requested, expand axisymmetric to 3D
        [sensor_data, parameters, trans_pos, focus_pos, ...
            segmentation, medium_masks, kwave_medium, kgrid, source, source_labels] = ...
            convert_axisymmetric_to_3d(...
            sensor_data, parameters, trans_pos, focus_pos, ...
            segmentation, medium_masks, kwave_medium, source, source_labels);
    else
        % otherwise retain 2D output (axisymmetric expanded to 2D)
        [sensor_data, parameters, trans_pos, focus_pos, ...
            segmentation, medium_masks, kwave_medium, kgrid, source, source_labels] = ...
            convert_axisymmetric_to_2d(...
            sensor_data, parameters, trans_pos, focus_pos, ...
            segmentation, medium_masks, kwave_medium, source, source_labels);
    end